CREATE OR REPLACE TABLE `anbc-hcb-dev.provider_ds_netconf_data_hcb_dev.A870800_medicare_supply_demand_ref_specialty_crosswalk`
OPTIONS (labels=[("owner", "deepan_thulasi_aetna_com")])
AS
SELECT * FROM UNNEST([
  STRUCT('Primary Care'                  AS cms_specialty, 'FP'   AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Primary Care'                  AS cms_specialty, 'I'    AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Allergy and Immunology'        AS cms_specialty, 'A'    AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Cardiology'                    AS cms_specialty, 'C'    AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Chiropractor'                  AS cms_specialty, 'VVCH' AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Clinical Psychology'           AS cms_specialty, 'VVMH' AS aetna_cd, 'proxy'   AS match_type, TRUE  AS inflated),
  STRUCT('Clinical Social Work'          AS cms_specialty, 'VVMH' AS aetna_cd, 'proxy'   AS match_type, TRUE  AS inflated),
  STRUCT('Dermatology'                   AS cms_specialty, 'D'    AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Endocrinology'                 AS cms_specialty, 'E'    AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('ENT/Otolaryngology'            AS cms_specialty, 'EN'   AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Gastroenterology'              AS cms_specialty, 'G'    AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('General Surgery'               AS cms_specialty, 'S'    AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Gynecology OB/GYN'             AS cms_specialty, 'OG'   AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Infectious Diseases'           AS cms_specialty, 'II'   AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Nephrology'                    AS cms_specialty, 'N'    AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Neurology'                     AS cms_specialty, 'NE'   AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Neurosurgery'                  AS cms_specialty, 'NS'   AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Oncology Medical/Surgical'     AS cms_specialty, 'H'    AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Oncology Radiation'            AS cms_specialty, 'RO'   AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Ophthalmology'                 AS cms_specialty, 'O'    AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Orthopedic Surgery'            AS cms_specialty, 'OR'   AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Physiatry Rehabilitative Med'  AS cms_specialty, 'VVRH' AS aetna_cd, 'proxy'   AS match_type, TRUE  AS inflated),
  STRUCT('Plastic Surgery'               AS cms_specialty, 'PS'   AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Podiatry'                      AS cms_specialty, 'VVPD' AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Psychiatry'                    AS cms_specialty, 'PY'   AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Pulmonology'                   AS cms_specialty, 'PD'   AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Rheumatology'                  AS cms_specialty, 'RH'   AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Urology'                       AS cms_specialty, 'U'    AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Vascular Surgery'              AS cms_specialty, 'VS'   AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Cardiothoracic Surgery'        AS cms_specialty, 'CS'   AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Acute Inpatient Hospitals'     AS cms_specialty, 'WHOS' AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Cardiac Surgery Program'       AS cms_specialty, 'CS'   AS aetna_cd, 'proxy'   AS match_type, TRUE  AS inflated),
  STRUCT('Cardiac Catheterization'       AS cms_specialty, 'C'    AS aetna_cd, 'proxy'   AS match_type, TRUE  AS inflated),
  STRUCT('Critical Care ICU'             AS cms_specialty, 'VICU' AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Surgical Services ASC'         AS cms_specialty, 'WASF' AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Skilled Nursing Facility'      AS cms_specialty, 'WLTC' AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Diagnostic Radiology'          AS cms_specialty, 'WRAD' AS aetna_cd, 'exact'    AS match_type, FALSE AS inflated),
  STRUCT('Mammography'                   AS cms_specialty, 'VRAD' AS aetna_cd, 'proxy'   AS match_type, TRUE  AS inflated),
  STRUCT('Physical Therapy'              AS cms_specialty, 'VVRH' AS aetna_cd, 'proxy'   AS match_type, TRUE  AS inflated),
  STRUCT('Occupational Therapy'          AS cms_specialty, 'VVRH' AS aetna_cd, 'proxy'   AS match_type, TRUE  AS inflated),
  STRUCT('Speech Therapy'                AS cms_specialty, 'VVRH' AS aetna_cd, 'proxy'   AS match_type, TRUE  AS inflated),
  STRUCT('Inpatient Psychiatric'         AS cms_specialty, 'WBHF' AS aetna_cd, 'proxy'   AS match_type, TRUE  AS inflated),
  STRUCT('Outpatient Infusion/Chemo'     AS cms_specialty, 'WHOS' AS aetna_cd, 'proxy'   AS match_type, TRUE  AS inflated),
  STRUCT('Outpatient Behavioral Health'  AS cms_specialty, 'WBHF' AS aetna_cd, 'proxy'   AS match_type, TRUE  AS inflated)
])
