CREATE OR REPLACE TABLE `anbc-hcb-dev.provider_ds_netconf_data_hcb_dev.A870800_medicare_supply_demand_ref_time_distance`
OPTIONS (labels=[("owner", "deepan_thulasi_aetna_com")])
AS
SELECT * FROM UNNEST([
  -- Primary Care
  STRUCT('Primary Care' AS cms_specialty, 'Large Metro' AS county_type, 10 AS max_time_min, 5  AS max_distance_miles),
  STRUCT('Primary Care', 'Metro',       15, 10),
  STRUCT('Primary Care', 'Micro',       30, 20),
  STRUCT('Primary Care', 'Rural',       40, 30),
  STRUCT('Primary Care', 'CEAC',        70, 60),
  -- Allergy and Immunology
  STRUCT('Allergy and Immunology', 'Large Metro', 30, 15),
  STRUCT('Allergy and Immunology', 'Metro',       45, 30),
  STRUCT('Allergy and Immunology', 'Micro',       80, 60),
  STRUCT('Allergy and Immunology', 'Rural',       90, 75),
  STRUCT('Allergy and Immunology', 'CEAC',       125,110),
  -- Cardiology
  STRUCT('Cardiology', 'Large Metro', 20, 10),
  STRUCT('Cardiology', 'Metro',       30, 20),
  STRUCT('Cardiology', 'Micro',       50, 35),
  STRUCT('Cardiology', 'Rural',       75, 60),
  STRUCT('Cardiology', 'CEAC',        95, 85),
  -- Chiropractor
  STRUCT('Chiropractor', 'Large Metro', 30, 15),
  STRUCT('Chiropractor', 'Metro',       45, 30),
  STRUCT('Chiropractor', 'Micro',       80, 60),
  STRUCT('Chiropractor', 'Rural',       90, 75),
  STRUCT('Chiropractor', 'CEAC',       125,110),
  -- Clinical Psychology
  STRUCT('Clinical Psychology', 'Large Metro', 20, 10),
  STRUCT('Clinical Psychology', 'Metro',       45, 30),
  STRUCT('Clinical Psychology', 'Micro',       60, 45),
  STRUCT('Clinical Psychology', 'Rural',       75, 60),
  STRUCT('Clinical Psychology', 'CEAC',       145,130),
  -- Clinical Social Work
  STRUCT('Clinical Social Work', 'Large Metro', 20, 10),
  STRUCT('Clinical Social Work', 'Metro',       30, 20),
  STRUCT('Clinical Social Work', 'Micro',       50, 35),
  STRUCT('Clinical Social Work', 'Rural',       75, 60),
  STRUCT('Clinical Social Work', 'CEAC',       125,110),
  -- Dermatology
  STRUCT('Dermatology', 'Large Metro', 20, 10),
  STRUCT('Dermatology', 'Metro',       45, 30),
  STRUCT('Dermatology', 'Micro',       60, 45),
  STRUCT('Dermatology', 'Rural',       75, 60),
  STRUCT('Dermatology', 'CEAC',       110,100),
  -- Endocrinology
  STRUCT('Endocrinology', 'Large Metro', 30, 15),
  STRUCT('Endocrinology', 'Metro',       60, 40),
  STRUCT('Endocrinology', 'Micro',      100, 75),
  STRUCT('Endocrinology', 'Rural',      110, 90),
  STRUCT('Endocrinology', 'CEAC',       145,130),
  -- ENT/Otolaryngology
  STRUCT('ENT/Otolaryngology', 'Large Metro', 30, 15),
  STRUCT('ENT/Otolaryngology', 'Metro',       45, 30),
  STRUCT('ENT/Otolaryngology', 'Micro',       80, 60),
  STRUCT('ENT/Otolaryngology', 'Rural',       90, 75),
  STRUCT('ENT/Otolaryngology', 'CEAC',       125,110),
  -- Gastroenterology
  STRUCT('Gastroenterology', 'Large Metro', 20, 10),
  STRUCT('Gastroenterology', 'Metro',       45, 30),
  STRUCT('Gastroenterology', 'Micro',       60, 45),
  STRUCT('Gastroenterology', 'Rural',       75, 60),
  STRUCT('Gastroenterology', 'CEAC',       110,100),
  -- General Surgery
  STRUCT('General Surgery', 'Large Metro', 20, 10),
  STRUCT('General Surgery', 'Metro',       30, 20),
  STRUCT('General Surgery', 'Micro',       50, 35),
  STRUCT('General Surgery', 'Rural',       75, 60),
  STRUCT('General Surgery', 'CEAC',        95, 85),
  -- Gynecology OB/GYN
  STRUCT('Gynecology OB/GYN', 'Large Metro', 30, 15),
  STRUCT('Gynecology OB/GYN', 'Metro',       45, 30),
  STRUCT('Gynecology OB/GYN', 'Micro',       80, 60),
  STRUCT('Gynecology OB/GYN', 'Rural',       90, 75),
  STRUCT('Gynecology OB/GYN', 'CEAC',       125,110),
  -- Infectious Diseases
  STRUCT('Infectious Diseases', 'Large Metro', 30, 15),
  STRUCT('Infectious Diseases', 'Metro',       60, 40),
  STRUCT('Infectious Diseases', 'Micro',      100, 75),
  STRUCT('Infectious Diseases', 'Rural',      110, 90),
  STRUCT('Infectious Diseases', 'CEAC',       145,130),
  -- Nephrology
  STRUCT('Nephrology', 'Large Metro', 30, 15),
  STRUCT('Nephrology', 'Metro',       45, 30),
  STRUCT('Nephrology', 'Micro',       80, 60),
  STRUCT('Nephrology', 'Rural',       90, 75),
  STRUCT('Nephrology', 'CEAC',       125,110),
  -- Neurology
  STRUCT('Neurology', 'Large Metro', 20, 10),
  STRUCT('Neurology', 'Metro',       45, 30),
  STRUCT('Neurology', 'Micro',       60, 45),
  STRUCT('Neurology', 'Rural',       75, 60),
  STRUCT('Neurology', 'CEAC',       110,100),
  -- Neurosurgery
  STRUCT('Neurosurgery', 'Large Metro', 30, 15),
  STRUCT('Neurosurgery', 'Metro',       60, 40),
  STRUCT('Neurosurgery', 'Micro',      100, 75),
  STRUCT('Neurosurgery', 'Rural',      110, 90),
  STRUCT('Neurosurgery', 'CEAC',       145,130),
  -- Oncology Medical/Surgical
  STRUCT('Oncology Medical/Surgical', 'Large Metro', 20, 10),
  STRUCT('Oncology Medical/Surgical', 'Metro',       45, 30),
  STRUCT('Oncology Medical/Surgical', 'Micro',       60, 45),
  STRUCT('Oncology Medical/Surgical', 'Rural',       75, 60),
  STRUCT('Oncology Medical/Surgical', 'CEAC',       110,100),
  -- Oncology Radiation
  STRUCT('Oncology Radiation', 'Large Metro', 30, 15),
  STRUCT('Oncology Radiation', 'Metro',       60, 40),
  STRUCT('Oncology Radiation', 'Micro',      100, 75),
  STRUCT('Oncology Radiation', 'Rural',      110, 90),
  STRUCT('Oncology Radiation', 'CEAC',       145,130),
  -- Ophthalmology
  STRUCT('Ophthalmology', 'Large Metro', 20, 10),
  STRUCT('Ophthalmology', 'Metro',       30, 20),
  STRUCT('Ophthalmology', 'Micro',       50, 35),
  STRUCT('Ophthalmology', 'Rural',       75, 60),
  STRUCT('Ophthalmology', 'CEAC',        95, 85),
  -- Orthopedic Surgery
  STRUCT('Orthopedic Surgery', 'Large Metro', 20, 10),
  STRUCT('Orthopedic Surgery', 'Metro',       30, 20),
  STRUCT('Orthopedic Surgery', 'Micro',       50, 35),
  STRUCT('Orthopedic Surgery', 'Rural',       75, 60),
  STRUCT('Orthopedic Surgery', 'CEAC',        95, 85),
  -- Physiatry Rehabilitative Med
  STRUCT('Physiatry Rehabilitative Med', 'Large Metro', 30, 15),
  STRUCT('Physiatry Rehabilitative Med', 'Metro',       45, 30),
  STRUCT('Physiatry Rehabilitative Med', 'Micro',       80, 60),
  STRUCT('Physiatry Rehabilitative Med', 'Rural',       90, 75),
  STRUCT('Physiatry Rehabilitative Med', 'CEAC',       125,110),
  -- Plastic Surgery
  STRUCT('Plastic Surgery', 'Large Metro', 30, 15),
  STRUCT('Plastic Surgery', 'Metro',       60, 40),
  STRUCT('Plastic Surgery', 'Micro',      100, 75),
  STRUCT('Plastic Surgery', 'Rural',      110, 90),
  STRUCT('Plastic Surgery', 'CEAC',       145,130),
  -- Podiatry
  STRUCT('Podiatry', 'Large Metro', 20, 10),
  STRUCT('Podiatry', 'Metro',       45, 30),
  STRUCT('Podiatry', 'Micro',       60, 45),
  STRUCT('Podiatry', 'Rural',       75, 60),
  STRUCT('Podiatry', 'CEAC',       110,100),
  -- Psychiatry
  STRUCT('Psychiatry', 'Large Metro', 20, 10),
  STRUCT('Psychiatry', 'Metro',       45, 30),
  STRUCT('Psychiatry', 'Micro',       60, 45),
  STRUCT('Psychiatry', 'Rural',       75, 60),
  STRUCT('Psychiatry', 'CEAC',       110,100),
  -- Pulmonology
  STRUCT('Pulmonology', 'Large Metro', 20, 10),
  STRUCT('Pulmonology', 'Metro',       45, 30),
  STRUCT('Pulmonology', 'Micro',       60, 45),
  STRUCT('Pulmonology', 'Rural',       75, 60),
  STRUCT('Pulmonology', 'CEAC',       110,100),
  -- Rheumatology
  STRUCT('Rheumatology', 'Large Metro', 30, 15),
  STRUCT('Rheumatology', 'Metro',       60, 40),
  STRUCT('Rheumatology', 'Micro',      100, 75),
  STRUCT('Rheumatology', 'Rural',      110, 90),
  STRUCT('Rheumatology', 'CEAC',       145,130),
  -- Urology
  STRUCT('Urology', 'Large Metro', 20, 10),
  STRUCT('Urology', 'Metro',       45, 30),
  STRUCT('Urology', 'Micro',       60, 45),
  STRUCT('Urology', 'Rural',       75, 60),
  STRUCT('Urology', 'CEAC',       110,100),
  -- Vascular Surgery
  STRUCT('Vascular Surgery', 'Large Metro', 30, 15),
  STRUCT('Vascular Surgery', 'Metro',       60, 40),
  STRUCT('Vascular Surgery', 'Micro',      100, 75),
  STRUCT('Vascular Surgery', 'Rural',      110, 90),
  STRUCT('Vascular Surgery', 'CEAC',       145,130),
  -- Cardiothoracic Surgery
  STRUCT('Cardiothoracic Surgery', 'Large Metro', 30, 15),
  STRUCT('Cardiothoracic Surgery', 'Metro',       60, 40),
  STRUCT('Cardiothoracic Surgery', 'Micro',      100, 75),
  STRUCT('Cardiothoracic Surgery', 'Rural',      110, 90),
  STRUCT('Cardiothoracic Surgery', 'CEAC',       145,130),
  -- Acute Inpatient Hospitals
  STRUCT('Acute Inpatient Hospitals', 'Large Metro', 20, 10),
  STRUCT('Acute Inpatient Hospitals', 'Metro',       45, 30),
  STRUCT('Acute Inpatient Hospitals', 'Micro',       80, 60),
  STRUCT('Acute Inpatient Hospitals', 'Rural',       75, 60),
  STRUCT('Acute Inpatient Hospitals', 'CEAC',       110,100),
  -- Cardiac Surgery Program
  STRUCT('Cardiac Surgery Program', 'Large Metro', 30, 15),
  STRUCT('Cardiac Surgery Program', 'Metro',       60, 40),
  STRUCT('Cardiac Surgery Program', 'Micro',      160,120),
  STRUCT('Cardiac Surgery Program', 'Rural',      145,120),
  STRUCT('Cardiac Surgery Program', 'CEAC',       155,140),
  -- Cardiac Catheterization
  STRUCT('Cardiac Catheterization', 'Large Metro', 30, 15),
  STRUCT('Cardiac Catheterization', 'Metro',       60, 40),
  STRUCT('Cardiac Catheterization', 'Micro',      160,120),
  STRUCT('Cardiac Catheterization', 'Rural',      145,120),
  STRUCT('Cardiac Catheterization', 'CEAC',       155,140),
  -- Critical Care ICU
  STRUCT('Critical Care ICU', 'Large Metro', 20, 10),
  STRUCT('Critical Care ICU', 'Metro',       45, 30),
  STRUCT('Critical Care ICU', 'Micro',      160,120),
  STRUCT('Critical Care ICU', 'Rural',      145,120),
  STRUCT('Critical Care ICU', 'CEAC',       155,140),
  -- Surgical Services ASC
  STRUCT('Surgical Services ASC', 'Large Metro', 20, 10),
  STRUCT('Surgical Services ASC', 'Metro',       45, 30),
  STRUCT('Surgical Services ASC', 'Micro',       80, 60),
  STRUCT('Surgical Services ASC', 'Rural',       75, 60),
  STRUCT('Surgical Services ASC', 'CEAC',       110,100),
  -- Skilled Nursing Facility
  STRUCT('Skilled Nursing Facility', 'Large Metro', 20, 10),
  STRUCT('Skilled Nursing Facility', 'Metro',       45, 30),
  STRUCT('Skilled Nursing Facility', 'Micro',       80, 60),
  STRUCT('Skilled Nursing Facility', 'Rural',       75, 60),
  STRUCT('Skilled Nursing Facility', 'CEAC',        95, 85),
  -- Diagnostic Radiology
  STRUCT('Diagnostic Radiology', 'Large Metro', 20, 10),
  STRUCT('Diagnostic Radiology', 'Metro',       45, 30),
  STRUCT('Diagnostic Radiology', 'Micro',       80, 60),
  STRUCT('Diagnostic Radiology', 'Rural',       75, 60),
  STRUCT('Diagnostic Radiology', 'CEAC',       110,100),
  -- Mammography
  STRUCT('Mammography', 'Large Metro', 20, 10),
  STRUCT('Mammography', 'Metro',       45, 30),
  STRUCT('Mammography', 'Micro',       80, 60),
  STRUCT('Mammography', 'Rural',       75, 60),
  STRUCT('Mammography', 'CEAC',       110,100),
  -- Physical Therapy
  STRUCT('Physical Therapy', 'Large Metro', 20, 10),
  STRUCT('Physical Therapy', 'Metro',       45, 30),
  STRUCT('Physical Therapy', 'Micro',       80, 60),
  STRUCT('Physical Therapy', 'Rural',       75, 60),
  STRUCT('Physical Therapy', 'CEAC',       110,100),
  -- Occupational Therapy
  STRUCT('Occupational Therapy', 'Large Metro', 20, 10),
  STRUCT('Occupational Therapy', 'Metro',       45, 30),
  STRUCT('Occupational Therapy', 'Micro',       80, 60),
  STRUCT('Occupational Therapy', 'Rural',       75, 60),
  STRUCT('Occupational Therapy', 'CEAC',       110,100),
  -- Speech Therapy
  STRUCT('Speech Therapy', 'Large Metro', 20, 10),
  STRUCT('Speech Therapy', 'Metro',       45, 30),
  STRUCT('Speech Therapy', 'Micro',       80, 60),
  STRUCT('Speech Therapy', 'Rural',       75, 60),
  STRUCT('Speech Therapy', 'CEAC',       110,100),
  -- Inpatient Psychiatric
  STRUCT('Inpatient Psychiatric', 'Large Metro', 30, 15),
  STRUCT('Inpatient Psychiatric', 'Metro',       70, 45),
  STRUCT('Inpatient Psychiatric', 'Micro',      100, 75),
  STRUCT('Inpatient Psychiatric', 'Rural',       90, 75),
  STRUCT('Inpatient Psychiatric', 'CEAC',       155,140),
  -- Outpatient Infusion/Chemo
  STRUCT('Outpatient Infusion/Chemo', 'Large Metro', 20, 10),
  STRUCT('Outpatient Infusion/Chemo', 'Metro',       45, 30),
  STRUCT('Outpatient Infusion/Chemo', 'Micro',       80, 60),
  STRUCT('Outpatient Infusion/Chemo', 'Rural',       75, 60),
  STRUCT('Outpatient Infusion/Chemo', 'CEAC',       110,100),
  -- Outpatient Behavioral Health
  STRUCT('Outpatient Behavioral Health', 'Large Metro', 20, 10),
  STRUCT('Outpatient Behavioral Health', 'Metro',       40, 25),
  STRUCT('Outpatient Behavioral Health', 'Micro',       55, 40),
  STRUCT('Outpatient Behavioral Health', 'Rural',       60, 50),
  STRUCT('Outpatient Behavioral Health', 'CEAC',       110,100)
])
