"""
whatif_dashboard_v2.py - v2: tabs, filters, methodology   [Plotly Dash]

v2 of the wired MVP dashboard (whatif_dashboard.py stays untouched).
Port 8051; proxy prefix from DASH_PROXY_PREFIX, default "/proxy/8051/"
(always applied - no env dependence).
Loads the EIGHT parquet extracts + manifest.json from ./extracts/ once
at startup; no file reads after startup. Tabs: (1) Simulator - state ->
county cascade with county names, OTHER_CONDITION term closed into the
demand bracket so baseline reproduces 2025 actuals exactly up to the
clamped calibration cells, name-matched provider table, collapsible
number tables, glossary hover text; (2) How the numbers flow - the
six-stage plain-language flow; (3) How it works - methodology, inputs,
assumptions, glossary; (4) Model details - coefficient explorer, fit
quality, evidence and freshness cards; (5) County Risk (DASH-2) - wired
to the capacity v2 tables (cap_county_risk + cap_fill_result +
cap_provider_year) loaded ONCE at startup via the expanded_scope config
pattern (adds google-cloud-bigquery as a startup dependency; tab degrades
to an error card without it), sliders shared with the Simulator, in-python
two-pass refill mirroring module 69 (DASH-A1 approximation). Screen text
says "local care pattern" for the calibration factor; code and table
names unchanged.
Demand cascade:
  demand[spec] = local_pattern[county, spec] x (
      sum_b members_b x BASE_RATE[spec]
    + sum_{b,c} members_b x prevalence[county, b, c] x rate[c, spec]
    + sum_b members_b x other_prevalence[county, b] x
      rate[OTHER_CONDITION, spec])
Run: python model_and_dashboard_v1/07_dashboard/whatif_dashboard_v2.py
Deps: dash, plotly, pandas, pyarrow. Extracts must be regenerated by
21_dashboard_extracts.py (eight-file set) before first launch.
"""

import json
import os

import pandas as pd
import plotly.graph_objects as go
from dash import Dash, Input, Output, State, ctx, dash_table, dcc, html, no_update
from dash.exceptions import PreventUpdate

BANDS = ["60-64", "65-74", "75-84", "85p"]
BAND_NAMES = ["60-64", "65-74", "75-84", "85+"]
MASTER_DEFAULT = 0
BAND_DEFAULTS = [0, 0, 0, 0]
TOP_PROVIDERS_SHOWN = 50
TOP_PROVIDERS_STORED_PER_SPEC = 50
DEFAULT_STATE = "FL"

GRAY = "#c3c2b7"
GREEN = "#0ca30c"
ACCENT_DATA = "#e8f4e8"
ACCENT_MODEL = "#e6eefb"
NEUTRAL_BOX = "#f4f4f2"

GLOSSARY = {
    "prevalence": "The share of members in a county and age group who "
                  "hold a condition, counted from 2025 claims.",
    "base rate": "Visits per member that everyone makes regardless of "
                 "conditions - the regression intercept.",
    "visit rate": "Extra visits per year that one condition adds in one "
                  "specialty - a fitted regression coefficient.",
    "local care pattern": "Actual 2025 visits divided by the formula's "
                          "2025 number, per county and specialty. Anchors "
                          "the baseline to local reality and resizes every "
                          "slider change to local behavior.",
    "intake weight": "The provider's share of last year's new patients "
                     "in their county and specialty - how new demand is "
                     "split among providers.",
    "ceiling": "v0 placeholder capacity: the provider's busiest observed "
               "month (2024-2025) times 12. A model replaces this later.",
    "headroom": "Ceiling minus load: how many more annual visits fit "
                "before the provider is at capacity.",
    "new demand": "The scenario's change in annual visits (delta) routed "
                  "to a provider via their intake weight.",
    "movement arrows": "^k / vk: the condition rose or fell k rank "
                       "positions versus baseline; - means unchanged.",
}


def _extract_dir():
    try:
        here = os.path.dirname(os.path.abspath(__file__))
    except NameError:
        here = os.getcwd()
    cand = os.path.join(here, "extracts")
    if os.path.isdir(cand):
        return cand
    probe = here
    for _ in range(6):
        cand = os.path.join(probe, "model_and_dashboard_v1", "07_dashboard",
                            "extracts")
        if os.path.isdir(cand):
            return cand
        probe = os.path.dirname(probe)
    raise FileNotFoundError(
        "extracts folder not found - run 21_dashboard_extracts.py first")


def load_extracts():
    d = _extract_dir()
    names = ["enrollment", "growth_context", "sickness_rates", "visit_rates",
             "county_calibration", "providers", "conditions_meta",
             "other_condition_prevalence"]
    frames = {}
    for n in names:
        path = os.path.join(d, f"{n}.parquet")
        if not os.path.isfile(path):
            raise FileNotFoundError(
                f"{n}.parquet missing - regenerate the eight-file extract "
                f"set with 21_dashboard_extracts.py")
        frames[n] = pd.read_parquet(path)
    with open(os.path.join(d, "manifest.json"), "r", encoding="utf-8") as f:
        manifest = json.load(f)
    return frames, manifest


FRAMES, MANIFEST = load_extracts()

ENR = FRAMES["enrollment"]
GROWTH = FRAMES["growth_context"]
SICK = FRAMES["sickness_rates"]
RATES = FRAMES["visit_rates"]
CAL = FRAMES["county_calibration"]
PROV = FRAMES["providers"]
META = FRAMES["conditions_meta"]
OTHER = FRAMES["other_condition_prevalence"]

COUNTY_STATE = dict(zip(ENR["mbr_county_cd"], ENR["state_cd"]))
COUNTY_MEMBERS = {
    cty: dict(zip(g["age_band"], g["members"]))
    for cty, g in ENR.groupby("mbr_county_cd")}
COUNTY_NAME = {}
if "county_name" in ENR.columns:
    COUNTY_NAME = dict(zip(ENR["mbr_county_cd"], ENR["county_name"]))
_county_totals = ENR.groupby("mbr_county_cd")["members"].sum()
STATES = sorted(set(COUNTY_STATE.values()))


def county_label(c):
    name = COUNTY_NAME.get(c)
    return f"{name} ({c})" if name else c


def state_counties(state):
    return sorted((c for c, s in COUNTY_STATE.items() if s == state),
                  key=lambda c: -_county_totals.get(c, 0))


def default_county(state):
    counties = state_counties(state)
    return counties[0] if counties else None


GROWTH_LOOKUP = {(r.mbr_county_cd, r.age_band): float(r.last_year_yoy_pct)
                 for r in GROWTH.itertuples()
                 if pd.notna(r.last_year_yoy_pct)}
_state_growth = GROWTH.dropna(subset=["last_year_yoy_pct"]) \
    .groupby(["state_cd", "age_band"])["last_year_yoy_pct"].mean()
STATE_GROWTH = {k: float(v) for k, v in _state_growth.items()}

SPECIALTIES = sorted(RATES["cms_specialty"].unique())
BASE_RATE = {r.cms_specialty: float(r.visit_rate)
             for r in RATES.itertuples() if r.condition == "BASE_RATE"}
OTHER_RATE = {r.cms_specialty: float(r.visit_rate)
              for r in RATES.itertuples()
              if r.condition == "OTHER_CONDITION"}
RATE_LOOKUP = {}
for r in RATES.itertuples():
    if r.condition in ("BASE_RATE", "OTHER_CONDITION"):
        continue
    if float(r.visit_rate) > 0:
        RATE_LOOKUP.setdefault(str(r.condition), {})[r.cms_specialty] = \
            float(r.visit_rate)

SPEC_R2 = {r.cms_specialty: (None if pd.isna(r.r2) else float(r.r2))
           for r in RATES.itertuples() if r.condition == "BASE_RATE"}
SPEC_DEFLATION = {}
if "deflation_factor" in RATES.columns:
    SPEC_DEFLATION = {
        r.cms_specialty: (None if pd.isna(r.deflation_factor)
                          else float(r.deflation_factor))
        for r in RATES.itertuples() if r.condition == "BASE_RATE"}

CAL_LOOKUP = {(r.mbr_county_cd, r.cms_specialty): float(r.calibration_factor)
              for r in CAL.itertuples()}

DESC = dict(zip(META["condition"].astype(str), META["description"]))

OTHER_PREV = {}
for r in OTHER.itertuples():
    key = r.mbr_county_cd
    if key not in OTHER_PREV:
        OTHER_PREV[key] = [0.0] * len(BANDS)
    if r.age_band in BANDS and pd.notna(r.other_prevalence):
        OTHER_PREV[key][BANDS.index(r.age_band)] = float(r.other_prevalence)


def _norm_county(name):
    n = str(name).upper().replace(".", "").strip()
    if n.startswith("SAINT "):
        n = "ST " + n[6:]
    return n


if "prvdr_state" not in PROV.columns:
    raise RuntimeError(
        "providers.parquet has no prvdr_state column - regenerate the "
        "extracts with 21_dashboard_extracts.py (provider state fix, D15)")


def growth_label(county, band):
    v = GROWTH_LOOKUP.get((county, band))
    if v is None:
        v = STATE_GROWTH.get((COUNTY_STATE.get(county), band))
    return f"last year: {v:+.1f}%" if v is not None else "last year: n/a"


def compute_demand(members_by_band, prev, other_prev, cal):
    total_members = sum(members_by_band)
    cond_members = {c: sum(members_by_band[b] * prev[c][b]
                           for b in range(len(BANDS)))
                    for c in prev}
    other_members = sum(members_by_band[b] * other_prev[b]
                        for b in range(len(BANDS)))
    demand = {}
    for s in SPECIALTIES:
        visits = total_members * BASE_RATE.get(s, 0.0)
        for c, n in cond_members.items():
            rate = RATE_LOOKUP.get(c, {}).get(s)
            if rate:
                visits += n * rate
        visits += other_members * OTHER_RATE.get(s, 0.0)
        demand[s] = cal.get(s, 1.0) * visits
    return demand, cond_members, other_members


def ranks_desc(values_by_key):
    order = sorted(values_by_key, key=lambda k: -values_by_key[k])
    return order, {k: pos + 1 for pos, k in enumerate(order)}


def county_payload(county):
    members = [int(COUNTY_MEMBERS.get(county, {}).get(b, 0)) for b in BANDS]
    labels = [growth_label(county, b) for b in BANDS]
    master_label = growth_label(county, "ALL_BANDS")

    slice_df = SICK[SICK["mbr_county_cd"] == county]
    prev = {}
    for r in slice_df.itertuples():
        cond = str(r.condition)
        if cond not in prev:
            prev[cond] = [0.0] * len(BANDS)
        if r.age_band in BANDS:
            prev[cond][BANDS.index(r.age_band)] = float(r.prevalence)
    other_prev = OTHER_PREV.get(county, [0.0] * len(BANDS))

    cal = {s: CAL_LOOKUP.get((county, s), 1.0) for s in SPECIALTIES}
    base_demand, base_conditions, base_other = compute_demand(
        members, prev, other_prev, cal)
    _, base_ranks = ranks_desc(base_conditions)

    name = COUNTY_NAME.get(county)
    state = COUNTY_STATE.get(county)
    matched = 0
    unk_names = 0
    if name and state:
        target = _norm_county(name)
        name_mask = PROV["prvdr_county_clean"].map(
            lambda x: _norm_county(x) == target)
        unk_names = int((name_mask & (PROV["prvdr_state"] == "UNK")).sum())
        prov = PROV[name_mask & (PROV["prvdr_state"] == state)]
        matched = len(prov)
    else:
        prov = PROV.iloc[0:0]
    if matched == 0:
        prov = PROV
        prov_mode = (f"0 providers matched to county "
                     f"{county_label(county)}; showing footprint-wide top "
                     f"providers (routing approximate)")
        if unk_names:
            prov_mode += (f"; {unk_names:,} same-named providers exist "
                          f"but carry unknown state (UNK) and are "
                          f"excluded from routing")
    else:
        prov_mode = (f"{matched:,} providers matched to "
                     f"{county_label(county)} in {state}")
        if unk_names:
            prov_mode += (f"; {unk_names:,} same-named providers with "
                          f"unknown state (UNK) excluded from the match "
                          f"and from routing")
    prov = prov.sort_values("visits_2025", ascending=False)
    prov = prov.groupby("cms_specialty", sort=False) \
               .head(TOP_PROVIDERS_STORED_PER_SPEC)
    providers = []
    for r in prov.itertuples():
        w = getattr(r, "intake_weight")
        providers.append({
            "id": str(r.epdb_dw_prvdr_id),
            "spec": r.cms_specialty,
            "visits": int(r.visits_2025),
            "ceiling": int(r.ceiling_annual_v0),
            "weight": None if pd.isna(w) else float(w),
        })

    return {
        "county": county,
        "members": members,
        "labels": labels,
        "master_label": master_label,
        "prev": prev,
        "other_prev": other_prev,
        "cal": cal,
        "base_demand": base_demand,
        "base_conditions": base_conditions,
        "base_other": base_other,
        "base_ranks": base_ranks,
        "providers": providers,
        "prov_mode": prov_mode,
    }


def fmt(n):
    return f"{n:,.0f}"


def pct(n):
    return f"{n:+.1%}"


def status_of(utilization):
    if utilization > 1.00:
        return "OVER CAPACITY"
    if utilization >= 0.90:
        return "AT CAPACITY"
    return "HEADROOM"


def cond_label(cond):
    desc = str(DESC.get(cond, "")).strip()
    return f"{desc[:40]} ({cond})" if desc else cond


def gloss(text, term):
    return html.Span(text, title=GLOSSARY.get(term, ""),
                     style={"textDecoration": "underline dotted",
                            "cursor": "help"})


TABLE_STYLE = {
    "style_table": {"overflowX": "auto"},
    "style_cell": {"fontFamily": "system-ui, sans-serif", "fontSize": "13px",
                   "padding": "6px 10px", "textAlign": "left"},
    "style_header": {"fontWeight": "600"},
}

PROXY_PREFIX = os.environ.get("DASH_PROXY_PREFIX") or "/proxy/8051/"
print(f"[startup] proxy prefix = {PROXY_PREFIX}", flush=True)
app = Dash(__name__, requests_pathname_prefix=PROXY_PREFIX)

SCOPE_TEXT = [
    "Demographic changes move condition counts, and condition counts move "
    "specialty demand - that chain is the actual arithmetic of this page, "
    "not an illustration.",
    "With all sliders at 0 the page reproduces 2025 actual visit levels "
    "per county and specialty, up to three known residuals: the 45 cells "
    "where the local care pattern factor was clamped to the 0.1..3.0 "
    "range, small county cells whose prevalence is suppressed (under 30 "
    "members), and the difference between the December member snapshot "
    "used here and the full-year membership the factor was fitted on. "
    "Slider deltas are shaped by the fitted condition-to-specialty rates "
    "and resized by the local care pattern.",
    "Capacity is a v0 placeholder: each provider's ceiling is their own "
    "busiest observed month (2024-2025) times 12 - observed data, not a "
    "model - and it is Aetna-relative: only Aetna claims are visible, so a "
    "provider busy with other payers may look like they have room here "
    "when they do not.",
    "Routing assumes future patients choose providers the way past "
    "patients did: new demand flows in proportion to historical "
    "new-patient shares. Prevalence, visit rates and local care patterns "
    "are frozen during simulation; the sliders move enrollment only.",
    "This tool is directional, not a precise forecaster.",
]

MANIFEST_LINE = (f"extracts built {MANIFEST.get('built_at', 'n/a')} - "
                 f"{MANIFEST.get('note', '')}")


def kpi_tile(tile_id, label, term=None):
    label_el = gloss(label, term) if term else label
    return html.Div(style={"flex": "1", "minWidth": "170px",
                           "background": "#fcfcfb",
                           "border": "1px solid rgba(11,11,11,0.10)",
                           "borderRadius": "10px", "padding": "10px 14px"},
                    children=[
                        html.Div(label_el, style={"fontSize": "12px",
                                                  "color": "#52514e"}),
                        html.Div(id=tile_id,
                                 style={"fontSize": "24px",
                                        "fontWeight": "650"}),
                    ])


def slider_marks(mn, mx):
    return {i: (str(i) if i <= 0 else f"+{i}")
            for i in range(mn, mx + 1, 10)}


def slider_block(slider_id, readout_id, info_id, label, mn, mx, marks):
    return html.Div(style={"marginBottom": "16px"}, children=[
        html.Div(style={"display": "flex", "justifyContent": "space-between",
                        "alignItems": "baseline"},
                 children=[
                     html.Label(label, style={"fontSize": "13px",
                                              "fontWeight": "600"}),
                     html.Span(id=info_id,
                               title="Last year's actual December-to-"
                                     "December change - context only, never "
                                     "the starting position (D11).",
                               style={"fontSize": "11px",
                                      "color": "#2a78d6",
                                      "cursor": "help"}),
                 ]),
        dcc.Slider(id=slider_id, min=mn, max=mx, step=0.25, value=0,
                   marks=marks, tooltip={"placement": "bottom"}),
        html.Div(id=readout_id, style={"fontSize": "12px",
                                       "color": "#52514e"}),
    ])


def stage_box(number, title, source, color):
    return html.Div(style={"display": "flex", "gap": "16px",
                           "marginBottom": "4px"},
                    children=[
                        html.Div(style={"flex": "0 0 40%",
                                        "background": color,
                                        "border": "1px solid "
                                                  "rgba(11,11,11,0.12)",
                                        "borderRadius": "10px",
                                        "padding": "12px 16px"},
                                 children=[
                                     html.Div(f"{number}. {title}",
                                              style={"fontWeight": "650",
                                                     "fontSize": "14px"})]),
                        html.Div(source,
                                 style={"flex": "1", "fontSize": "13px",
                                        "color": "#3c3b38",
                                        "padding": "10px 4px"}),
                    ])


def arrow():
    return html.Div("↓", style={"textAlign": "left",
                                     "marginLeft": "18%",
                                     "fontSize": "20px",
                                     "color": "#898781",
                                     "margin": "2px 0 6px 18%"})


FLOW_STAGES = [
    (1, "Slider moves — your growth assumption.", NEUTRAL_BOX,
     "No data here — you set this. We tested predicting growth from "
     "history; last year's change pointed the wrong way, so the slider "
     "starts at 0 and we only show last year's change as a label."),
    (2, "New member counts per age group.", ACCENT_DATA,
     "Real enrollment: members per county per age group, counted from "
     "membership records (Dec 2025). The slider applies to these counts. "
     "Example: 1,000 members aged 85+, slider +10% = 100 new members."),
    (3, "Condition mix — people, not visits yet.", ACCENT_DATA,
     "From 2025 claims we counted, per county and age group, the share of "
     "members with each condition — the prevalence. New members x "
     "prevalence = new members with each condition. Example: 100 x 30% = "
     "30 new CKD members. This is the condition table."),
    (4, "Visits per specialty — what each condition adds.", ACCENT_MODEL,
     "The one fitted model. One row per member (1.58M, 2025): 56 yes/no "
     "condition flags -> visit counts per specialty (a visit = one member, "
     "one provider, one day). A regression per specialty gives the base "
     "visits everyone makes plus a coefficient per condition — those "
     "coefficients are the visit rates. Example: 30 CKD members x 2.8 = "
     "84 nephrology visits — the model's job ends at per-member visits; "
     "everything after is addition and a sharing rule."),
    (5, "Local care pattern — anchor to this county's reality.",
     ACCENT_DATA,
     "The formula uses national patterns; counties have local habits. Per "
     "county and specialty: actual 2025 visits divided by the formula's "
     "2025 number = the factor. Baseline matches reality exactly, and "
     "every slider change is resized to local behavior. Example: factor "
     "0.9 -> 84 becomes 76."),
    (6, "County demand per specialty — add everyone up.", NEUTRAL_BOX,
     "Each member's predicted visits are summed to the county total per "
     "specialty. No model here — just addition. This is the number on "
     "the demand charts."),
    (7, "Providers — who absorbs the change.", NEUTRAL_BOX,
     "A sharing rule, not a model: each provider takes a share of the new "
     "demand equal to their share of last year's new patients in that "
     "county and specialty (intake weight). That load is checked against "
     "their ceiling — currently v0: busiest observed month x 12. Modeling "
     "who patients actually choose is a future improvement, listed in "
     "assumptions."),
]


def flow_tab():
    children = [
        html.H3("How the numbers flow"),
        html.Div("Boxes: gray = you set it / what you see; green = counted "
                 "from data; blue = fitted model.",
                 style={"fontSize": "12px", "color": "#52514e",
                        "marginBottom": "12px"}),
    ]
    for i, (num, title, color, source) in enumerate(FLOW_STAGES):
        children.append(stage_box(num, title, source, color))
        if i < len(FLOW_STAGES) - 1:
            children.append(arrow())
    children.append(html.Div(
        style={"border": "2px solid rgba(11,11,11,0.25)",
               "borderRadius": "10px", "padding": "14px 18px",
               "marginTop": "18px", "background": "#fcfcfb",
               "maxWidth": "820px"},
        children=[
            html.Div("Worked example", style={"fontWeight": "650",
                                              "marginBottom": "6px"}),
            html.Div("100 new 85+ members -> x30% = 30 CKD members -> "
                     "x2.8 = 84 nephrology visits -> x0.9 local pattern = "
                     "76 shown.",
                     style={"fontSize": "13px"}),
        ]))
    return html.Div(children, style={"maxWidth": "980px", "padding": "12px"})


INPUTS_ROWS = [
    {"input": "enrollment", "source": "membership records (Dec 2025)",
     "plain_words": "how many members live in each county, by age group",
     "grain": "county x age group"},
    {"input": "sickness rates", "source": "2025 claims diagnoses",
     "plain_words": "share of members holding each condition",
     "grain": "county x age group x condition"},
    {"input": "visit rates", "source": "fitted regression (one per "
                                       "specialty)",
     "plain_words": "base visits everyone makes + extra visits each "
                    "condition adds",
     "grain": "specialty x condition"},
    {"input": "local care pattern", "source": "actual 2025 visits vs the "
                                              "formula's 2025 number",
     "plain_words": "how this county's real utilization compares to the "
                    "national pattern",
     "grain": "county x specialty"},
    {"input": "providers", "source": "2024-2025 claims per provider",
     "plain_words": "current visits, observed-peak ceiling (v0), share of "
                    "new patients",
     "grain": "provider"},
    {"input": "growth context", "source": "December-to-December enrollment "
                                          "change",
     "plain_words": "last year's change, shown as a label only",
     "grain": "county x age group"},
]


def methodology_tab():
    return html.Div(style={"maxWidth": "900px", "padding": "12px",
                           "fontSize": "14px"}, children=[
        html.H3("How it works"),
        html.H4("The demand formula"),
        html.P("In words: take the members in each age group, apply the "
               "growth sliders, work out how many hold each condition, "
               "multiply by what each condition adds in each specialty, "
               "add the base visits everyone makes, then resize the total "
               "to this county's local care pattern."),
        html.P("In symbols: demand[specialty] = local_pattern x ( members "
               "x base_rate + sum over conditions of members_with_condition "
               "x visit_rate + members_with_other_conditions x other_rate )."),
        html.P("Mini example: 100 new 85+ members, 30% CKD prevalence, "
               "2.8 nephrology visits per CKD member, local pattern 0.9: "
               "100 x 30% = 30 members; 30 x 2.8 = 84 visits; 84 x 0.9 = "
               "76 visits added to nephrology."),
        html.H4("Condition mix"),
        html.P("Members can hold several conditions at once, so the "
               "condition column does not sum to enrollment. Conditions "
               "outside the 56 modeled ones are pooled into 'Other "
               "conditions (pooled)' with their own prevalence and rate."),
        html.H4("The growth label"),
        html.P("Sliders start at 0 (decision D11): we tested predicting "
               "growth from history and last year's change pointed the "
               "wrong way (enrollment is decided at the annual enrollment "
               "period, effective January 1). Last year's change appears "
               "as a label beside each slider - context, never a "
               "starting position."),
        html.H4("Routing"),
        html.P("New demand in a specialty is split among that county's "
               "providers by intake weight - each provider's share of "
               "last year's new patients. Providers whose county and "
               "specialty saw no new patients last year carry no weight "
               "and receive no routed demand."),
        html.H4("Capacity"),
        html.P("Today (v0 placeholder): each provider's ceiling = their "
               "busiest observed month x 12. Simple and honest — it's "
               "what they've proven they can do — but one hot month can "
               "overstate it, and a steadily growing provider gets "
               "understated. No modeling involved."),
        html.P("Coming (capacity model): a model predicts each provider's "
               "realistic yearly and monthly ceiling from their own "
               "pattern — volume trend, how fast they absorb new "
               "patients, the age mix they treat, and how similar "
               "providers behave near their limits. Validated by "
               "backtest: predict last year's ceilings from the year "
               "before, and check no provider actually exceeded them. "
               "Unlike demand, capacity is not calibrated — there is no "
               "observed 'true maximum' to calibrate against; validation "
               "replaces calibration here."),
        html.H4("Status definitions"),
        html.P("Load = current visits + new demand. Under 90% of ceiling "
               "= HEADROOM; 90-100% = AT CAPACITY; over 100% = OVER "
               "CAPACITY, shown as 'short by N'."),
        html.H4("Inputs"),
        dash_table.DataTable(
            columns=[{"name": c, "id": c} for c in
                     ["input", "source", "plain_words", "grain"]],
            data=INPUTS_ROWS, **TABLE_STYLE),
        html.H4("Assumptions"),
        html.P("Rates are frozen during simulation - the sliders move "
               "enrollment only. Capacity is Aetna-relative. Routing "
               "assumes past choice behavior. Conditions come from 2025 "
               "diagnoses, so first-year members can under-show "
               "conditions. Only CMS physician specialties are covered, "
               "by deliberate mapping policy. The local care pattern is "
               "fixed at its 2025 value."),
        html.H4("Glossary"),
        html.Div([html.Div([html.B(term.title()), html.Span(f" - {text}")],
                           style={"marginBottom": "6px"})
                  for term, text in GLOSSARY.items()],
                 style={"fontSize": "13px"}),
    ])


_cond_footprint = SICK.groupby(SICK["condition"].astype(str))[
    "members_with_condition"].sum()
_other_footprint = float(OTHER["members_with_other"].sum())
_total_members = float(ENR["members"].sum())


def base_rate_share(spec):
    base_v = _total_members * BASE_RATE.get(spec, 0.0)
    cond_v = sum(float(_cond_footprint.get(c, 0.0)) * r[spec]
                 for c, r in RATE_LOOKUP.items() if spec in r)
    cond_v += _other_footprint * OTHER_RATE.get(spec, 0.0)
    total = base_v + cond_v
    return base_v / total if total else None


FIT_ROWS = []
for s in SPECIALTIES:
    r2 = SPEC_R2.get(s)
    share = base_rate_share(s)
    defl = SPEC_DEFLATION.get(s)
    FIT_ROWS.append({
        "specialty": s,
        "r2": "n/a" if r2 is None else f"{r2:.3f}",
        "base_rate_share": "n/a" if share is None else f"{share:.0%}",
        "deflation_factor": "n/a" if defl is None else f"{defl:.3f}",
    })


def model_tab():
    return html.Div(style={"maxWidth": "980px", "padding": "12px"},
                    children=[
        html.H3("Model details"),
        html.H4("Coefficient explorer"),
        html.Div(style={"maxWidth": "420px", "marginBottom": "8px"},
                 children=[
                     dcc.Dropdown(id="dd-coef-spec", options=SPECIALTIES,
                                  value=("Primary Care"
                                         if "Primary Care" in SPECIALTIES
                                         else SPECIALTIES[0]),
                                  clearable=False)]),
        html.Div(id="lbl-coef-base",
                 style={"fontSize": "13px", "fontWeight": "600",
                        "marginBottom": "4px"}),
        dcc.Graph(id="fig-coef", config={"displayModeBar": False}),
        html.Details(open=False, children=[
            html.Summary("Full coefficient table",
                         style={"fontWeight": "600", "cursor": "pointer"}),
            dash_table.DataTable(id="tbl-coef",
                                 columns=[{"name": c, "id": c} for c in
                                          ["condition", "visit_rate",
                                           "members_with_condition"]],
                                 **TABLE_STYLE),
        ]),
        html.H4("Fit quality"),
        html.Div("High r2 = condition-driven specialty; near-zero = visits "
                 "move with headcount, not sickness.",
                 style={"fontSize": "13px", "color": "#52514e",
                        "marginBottom": "6px"}),
        dash_table.DataTable(
            columns=[{"name": c, "id": c} for c in
                     ["specialty", "r2", "base_rate_share",
                      "deflation_factor"]],
            data=FIT_ROWS, **TABLE_STYLE),
        html.H4("Evidence"),
        html.Div(style={"border": "1px solid rgba(11,11,11,0.15)",
                        "borderRadius": "10px", "padding": "12px 16px",
                        "background": "#fcfcfb", "maxWidth": "680px",
                        "fontSize": "13px"},
                 children=[
                     "People with two conditions make fewer visits than "
                     "the two solo rates added together (median 0.68x). "
                     "That is why we fit an allocation model instead of "
                     "adding rates."]),
        html.H4("Freshness"),
        html.Div(style={"border": "1px solid rgba(11,11,11,0.15)",
                        "borderRadius": "10px", "padding": "12px 16px",
                        "background": "#fcfcfb", "maxWidth": "680px",
                        "fontSize": "13px"},
                 children=[
                     html.Div(MANIFEST_LINE),
                     html.Div(f"extract row counts: " + ", ".join(
                         f"{k.replace('.parquet', '')}="
                         f"{v.get('row_count'):,}"
                         for k, v in
                         MANIFEST.get("extracts", {}).items())),
                 ]),
    ])


def simulator_tab():
    return html.Div(children=[
        html.Div(style={"display": "flex", "gap": "16px",
                        "alignItems": "center", "marginBottom": "12px"},
                 children=[
                     html.Div(style={"minWidth": "120px"}, children=[
                         dcc.Dropdown(id="dd-state", options=STATES,
                                      value=DEFAULT_STATE,
                                      clearable=False)]),
                     html.Div(style={"minWidth": "320px"}, children=[
                         dcc.Dropdown(id="dd-county", clearable=False)]),
                     html.Button("Reset", id="btn-reset", n_clicks=0,
                                 style={"padding": "6px 18px",
                                        "fontSize": "13px",
                                        "cursor": "pointer"}),
                 ]),
        html.Details(open=True, style={"marginBottom": "14px"}, children=[
            html.Summary("Scope", style={"fontWeight": "600",
                                         "cursor": "pointer"}),
            html.Div([html.P(t) for t in SCOPE_TEXT],
                     style={"fontSize": "13px", "color": "#52514e",
                            "maxWidth": "820px"}),
        ]),
        html.Div(style={"display": "flex", "gap": "20px",
                        "alignItems": "flex-start"},
                 children=[
                     html.Div(style={"flex": "0 0 30%",
                                     "background": "#fcfcfb",
                                     "border": "1px solid "
                                               "rgba(11,11,11,0.10)",
                                     "borderRadius": "10px",
                                     "padding": "14px"},
                              children=[
                                  slider_block(
                                      "s-master", "r-master", "i-master",
                                      "Master: total enrollment (%)",
                                      -30, 50, slider_marks(-30, 50)),
                                  slider_block(
                                      "s-b0", "r-b0", "i-b0",
                                      "Band 60-64 (%)", -30, 100,
                                      slider_marks(-30, 100)),
                                  slider_block(
                                      "s-b1", "r-b1", "i-b1",
                                      "Band 65-74 (%)", -30, 100,
                                      slider_marks(-30, 100)),
                                  slider_block(
                                      "s-b2", "r-b2", "i-b2",
                                      "Band 75-84 (%)", -30, 100,
                                      slider_marks(-30, 100)),
                                  slider_block(
                                      "s-b3", "r-b3", "i-b3",
                                      "Band 85+ (%)", -30, 100,
                                      slider_marks(-30, 100)),
                                  html.Div("Moving the master sets every "
                                           "band to its value; band sliders "
                                           "then adjust one band at a time.",
                                           style={"fontSize": "12px",
                                                  "color": "#898781"}),
                                  html.Div("Defaults are 0 (D11): last "
                                           "year's change is context, "
                                           "never a starting position.",
                                           style={"fontSize": "12px",
                                                  "color": "#898781"}),
                              ]),
                     html.Div(style={"flex": "1"}, children=[
                         html.Div(style={"display": "flex", "gap": "12px",
                                         "flexWrap": "wrap",
                                         "marginBottom": "14px"},
                                  children=[
                                      kpi_tile("k-enroll",
                                               "Scenario total enrollment"),
                                      kpi_tile("k-visits",
                                               "Scenario total annual "
                                               "visits"),
                                      kpi_tile("k-at",
                                               "Providers at capacity",
                                               term="ceiling"),
                                      kpi_tile("k-over",
                                               "Providers over capacity",
                                               term="ceiling"),
                                  ]),
                         html.H4("Enrollment by band"),
                         dash_table.DataTable(
                             id="tbl-enroll",
                             columns=[{"name": c, "id": c} for c in
                                      ["band", "baseline", "scenario",
                                       "delta", "pct_change"]],
                             **TABLE_STYLE),
                         dcc.RadioItems(id="rad-topn",
                                        options=[{"label": "Top 10",
                                                  "value": 10},
                                                 {"label": "Top 20",
                                                  "value": 20}],
                                        value=10, inline=True,
                                        style={"fontSize": "13px",
                                               "margin": "14px 0 6px"},
                                        inputStyle={"marginRight": "4px"},
                                        labelStyle={"marginRight": "16px"}),
                         html.Div(style={"display": "flex", "gap": "16px",
                                         "alignItems": "flex-start"},
                                  children=[
                                      html.Div(style={"flex": "1",
                                                      "minWidth": "0"},
                                               children=[
                                                   dcc.Graph(
                                                       id="fig-specialty",
                                                       config={
                                                           "displayModeBar":
                                                           False})]),
                                      html.Div(style={"flex": "1",
                                                      "minWidth": "0"},
                                               children=[
                                                   dcc.Graph(
                                                       id="fig-condition",
                                                       config={
                                                           "displayModeBar":
                                                           False})]),
                                  ]),
                         html.H4(gloss("Condition mix", "prevalence")),
                         html.Div([
                             "Members can have multiple conditions; column "
                             "does not sum to enrollment. ",
                             gloss("Movement arrows", "movement arrows"),
                             " show rank changes vs baseline."],
                             style={"fontSize": "12px", "color": "#898781",
                                    "marginBottom": "6px"}),
                         html.Details(open=False, children=[
                             html.Summary("Show numbers",
                                          style={"fontWeight": "600",
                                                 "cursor": "pointer"}),
                             dash_table.DataTable(
                                 id="tbl-condition",
                                 columns=[{"name": c, "id": c} for c in
                                          ["rank", "movement", "condition",
                                           "baseline_members",
                                           "scenario_members",
                                           "delta", "pct_change"]],
                                 **TABLE_STYLE),
                         ]),
                         html.H4([
                             gloss("Demand by specialty", "visit rate"),
                             html.Span(f" ({len(SPECIALTIES)} fitted)",
                                       style={"fontWeight": "400",
                                              "fontSize": "13px"})]),
                         html.Div(style={"maxWidth": "520px",
                                         "marginBottom": "8px"},
                                  children=[
                                      dcc.Dropdown(id="dd-specialty",
                                                   options=SPECIALTIES,
                                                   value=SPECIALTIES,
                                                   multi=True)]),
                         html.Details(open=False, children=[
                             html.Summary("Show numbers",
                                          style={"fontWeight": "600",
                                                 "cursor": "pointer"}),
                             dash_table.DataTable(
                                 id="tbl-demand",
                                 columns=[{"name": c, "id": c} for c in
                                          ["specialty", "baseline_visits",
                                           "scenario_visits", "delta",
                                           "pct_change"]],
                                 **TABLE_STYLE),
                         ]),
                         html.H4([gloss("Provider load vs capacity",
                                        "ceiling"),
                                  html.Span(" (v0 placeholder ceilings)",
                                            style={"fontWeight": "400",
                                                   "fontSize": "13px"})]),
                         html.Div(id="lbl-provider-note",
                                  style={"fontSize": "12px",
                                         "color": "#898781",
                                         "marginBottom": "6px"}),
                         dash_table.DataTable(
                             id="tbl-provider",
                             columns=[{"name": c, "id": c} for c in
                                      ["provider", "specialty",
                                       "current_visits", "estimated_max",
                                       "new_demand_coming", "room_left",
                                       "status"]],
                             tooltip_header={
                                 "estimated_max": GLOSSARY["ceiling"],
                                 "new_demand_coming": GLOSSARY["new demand"],
                                 "room_left": GLOSSARY["headroom"],
                                 "status": "HEADROOM under 90%, AT "
                                           "CAPACITY 90-100%, OVER "
                                           "CAPACITY above 100% of the "
                                           "v0 ceiling.",
                             },
                             style_data_conditional=[
                                 {"if": {"filter_query":
                                         '{status} = "HEADROOM"',
                                         "column_id": "status"},
                                  "color": "#006300",
                                  "backgroundColor":
                                      "rgba(12,163,12,0.12)",
                                  "fontWeight": "600"},
                                 {"if": {"filter_query":
                                         '{status} = "AT CAPACITY"',
                                         "column_id": "status"},
                                  "color": "#8a5a00",
                                  "backgroundColor":
                                      "rgba(250,178,25,0.18)",
                                  "fontWeight": "600"},
                                 {"if": {"filter_query":
                                         '{status} = "OVER CAPACITY"',
                                         "column_id": "status"},
                                  "color": "#d03b3b",
                                  "backgroundColor":
                                      "rgba(208,59,59,0.14)",
                                  "fontWeight": "600"},
                             ],
                             **TABLE_STYLE),
                     ]),
                 ]),
    ])


# ---------------------------------------------------------------------------
# County Risk tab (DASH-2) - wired to the capacity v2 pipeline tables
# (cap_county_risk + cap_fill_result + cap_provider_year), loaded ONCE at
# startup via the expanded_scope config pattern (BigQuery; deviation from the
# parquet-extract pattern above, per the DASH-2 prompt). Slider math re-runs
# a simplified two-pass proportional fill IN PYTHON on precomputed arrays,
# mirroring module 69's lane logic on small data.
# DASH-A1 (approximation): the three source tables carry no hours-per-patient
# rate, so patient capacity per provider = (spare + uplift hours) / h, where
# h is calibrated per county x specialty from capacity-bound cells (budget /
# placed where unplaced > 0), falling back to the state x specialty median,
# then the global median.
# ---------------------------------------------------------------------------

import datetime as _dt
import sys as _sys
import urllib.request as _urlreq

SEGMENTS_8 = ["NEW_CHR_60_74", "NEW_CHR_75P", "NEW_NONCHR_60_74",
              "NEW_NONCHR_75P", "RET_CHR_60_74", "RET_CHR_75P",
              "RET_NONCHR_60_74", "RET_NONCHR_75P"]
RED_SCALE = [[0.0, "#fdecea"], [0.5, "#e4726a"], [1.0, "#7f1d1d"]]
UNATTRIBUTED = "Unattributed"


def _find_cfg():
    probe = os.path.dirname(os.path.abspath(__file__))
    for _ in range(6):
        cand = os.path.join(probe, "expanded_scope")
        if os.path.isfile(os.path.join(cand, "config.py")):
            return cand
        probe = os.path.dirname(probe)
    raise FileNotFoundError("expanded_scope/config.py not found")


def _load_cap_tables():
    try:
        _sys.path.insert(0, _find_cfg())
        import config as _cfg
        client = _cfg.client()
        risk = client.query(
            f"SELECT * FROM `{_cfg.table('cap_county_risk')}`"
        ).result().to_dataframe()
        fill = client.query(
            f"SELECT mbr_county_cd, mbr_state_cd, specialty_ctg_cd, "
            f"cms_specialty, segment_cd, npi, epdb_dw_prvdr_id, prvdr_county, "
            f"fill_lane_cd, absorbed_by, seg_market_share, placed_cnt, "
            f"unplaced_cnt, signal_src_cd "
            f"FROM `{_cfg.table('cap_fill_result')}`"
        ).result().to_dataframe()
        py = client.query(
            f"SELECT npi, epdb_dw_prvdr_id, prvdr_county, prvdr_state_cd, "
            f"specialty_ctg_cd, capped_hrs_yr, ceiling_low_hrs, spare_hrs, "
            f"team_uplift_hrs, util_ratio "
            f"FROM `{_cfg.table('cap_provider_year')}`"
        ).result().to_dataframe()
        return risk, fill, py, None
    except Exception as exc:                       # dashboard must still boot
        return None, None, None, str(exc)


CAP_RISK, CAP_FILL, CAP_PY, CAP_ERROR = _load_cap_tables()
CAP_LOADED_DATE = _dt.date.today().isoformat()


def _pid(row_npi, row_epdb):
    return str(row_npi) if pd.notna(row_npi) and str(row_npi) else str(row_epdb)


CAP_STORE = {}          # county_cd -> precomputed cell/provider arrays
CAP_STATES = []
BASE_VISITS_TOTAL = {}  # county_cd -> baseline 2025 formula visits (demand lens)

if CAP_ERROR is None:
    print(f"[county-risk] tables loaded: risk={len(CAP_RISK):,}, "
          f"fill={len(CAP_FILL):,}, provider_year={len(CAP_PY):,}",
          flush=True)

    # baseline county demand WITHOUT county_payload (that path re-scans and
    # name-matches the provider frame per county); one pass over each frame
    _prev_by_cty = {}
    for r in SICK.itertuples():
        d = _prev_by_cty.setdefault(r.mbr_county_cd, {})
        arr = d.setdefault(str(r.condition), [0.0] * len(BANDS))
        if r.age_band in BANDS and pd.notna(r.prevalence):
            arr[BANDS.index(r.age_band)] = float(r.prevalence)
    _cal_by_cty = {}
    for (cty, spec), v in CAL_LOOKUP.items():
        _cal_by_cty.setdefault(cty, {})[spec] = v
    for _cty in COUNTY_STATE:
        members = [int(COUNTY_MEMBERS.get(_cty, {}).get(b, 0)) for b in BANDS]
        demand, _, _ = compute_demand(
            members, _prev_by_cty.get(_cty, {}),
            OTHER_PREV.get(_cty, [0.0] * len(BANDS)),
            _cal_by_cty.get(_cty, {}))
        BASE_VISITS_TOTAL[_cty] = float(sum(demand.values()))
    print(f"[county-risk] baseline demand precomputed for "
          f"{len(BASE_VISITS_TOTAL):,} counties", flush=True)

    CAP_STATES = sorted(CAP_RISK["mbr_state_cd"].dropna().unique())

    _budget = {}
    for r in CAP_PY.itertuples():
        key = (_pid(r.npi, r.epdb_dw_prvdr_id), str(r.prvdr_county))
        _budget[key] = {
            "budget": float(r.spare_hrs or 0) + float(r.team_uplift_hrs or 0),
            "util_now": None if pd.isna(r.util_ratio) else float(r.util_ratio),
            "spec": r.specialty_ctg_cd,
            "state": r.prvdr_state_cd,
        }

    _prov_rows = CAP_FILL[CAP_FILL["absorbed_by"].isna()
                          & (CAP_FILL["npi"].notna()
                             | CAP_FILL["epdb_dw_prvdr_id"].notna())]
    _rem_rows = CAP_FILL[CAP_FILL["unplaced_cnt"].notna()]

    _unp_by_cell = {}
    for r in _rem_rows.itertuples():
        _unp_by_cell[(str(r.mbr_county_cd), str(r.specialty_ctg_cd),
                      str(r.segment_cd))] = float(r.unplaced_cnt or 0)

    _cells = {}
    for r in _prov_rows.itertuples():
        ck = (str(r.mbr_county_cd), str(r.specialty_ctg_cd), str(r.segment_cd))
        cell = _cells.setdefault(ck, {"providers": [], "placed_bl": 0.0,
                                      "cms": r.cms_specialty,
                                      "state": r.mbr_state_cd,
                                      "borrowed": 0.0})
        placed = float(r.placed_cnt or 0)
        cell["providers"].append({
            "pid": _pid(r.npi, r.epdb_dw_prvdr_id),
            "county": str(r.prvdr_county) if pd.notna(r.prvdr_county) else "",
            "share": float(r.seg_market_share or 0)})
        cell["placed_bl"] += placed
        if r.signal_src_cd == "BORROWED":
            cell["borrowed"] += placed

    _h_rate, _h_by_state_spec = {}, {}
    for (cty, spec, seg), cell in _cells.items():
        unp = _unp_by_cell.get((cty, spec, seg), 0.0)
        key = (cty, spec)
        agg = _h_rate.setdefault(key, {"placed": 0.0, "budget": 0.0,
                                       "bound": False, "state": cell["state"]})
        agg["placed"] += cell["placed_bl"]
        agg["bound"] = agg["bound"] or unp > 0.5
        for p in cell["providers"]:
            b = _budget.get((p["pid"], p["county"]))
            if b:
                agg["budget"] += b["budget"]
    for key, agg in _h_rate.items():
        if agg["bound"] and agg["placed"] > 0 and agg["budget"] > 0:
            h = agg["budget"] / agg["placed"]
            agg["h"] = h
            _h_by_state_spec.setdefault((agg["state"], key[1]), []).append(h)
    _h_global = sorted(h for lst in _h_by_state_spec.values() for h in lst)
    _h_global_med = _h_global[len(_h_global) // 2] if _h_global else 1.0
    for key, agg in _h_rate.items():
        if "h" not in agg:
            lst = sorted(_h_by_state_spec.get((agg["state"], key[1]), []))
            agg["h"] = lst[len(lst) // 2] if lst else _h_global_med
        agg["h"] = max(agg["h"], 0.1)

    # (cty, cms, seg) -> merged cell lookup, built ONCE (replaces the
    # quadratic risk-row x cells cross-match that hung startup). Two ctg
    # codes sharing one cms name merge their provider lists here, matching
    # how module 71 rolls risk up to cms grain.
    _cms_cells = {}
    for (cty, ctg, seg), cell in _cells.items():
        key = (cty, str(cell["cms"]) if pd.notna(cell["cms"]) else None, seg)
        agg = _cms_cells.setdefault(key, {"providers": [], "placed_bl": 0.0,
                                          "borrowed": 0.0, "ctg": ctg})
        agg["providers"].extend(cell["providers"])
        agg["placed_bl"] += cell["placed_bl"]
        agg["borrowed"] += cell["borrowed"]

    _EMPTY_CELL = {"providers": [], "placed_bl": 0.0, "borrowed": 0.0,
                   "ctg": None}
    for r in CAP_RISK.itertuples():
        cty = str(r.mbr_county_cd)
        store = CAP_STORE.setdefault(cty, {
            "state": r.mbr_state_cd, "cells": [], "providers": {}})
        spec = (str(r.cms_specialty) if pd.notna(r.cms_specialty)
                else None)
        seg = str(r.segment_cd) if pd.notna(r.segment_cd) else None
        growth = float(r.growth_demand or 0)
        fac = float(r.facility_absorbed_cnt or 0)
        cell_src = _cms_cells.get((cty, spec, seg)) or _EMPTY_CELL
        ctg = cell_src["ctg"]
        store["cells"].append({
            "cms": spec, "ctg": ctg, "seg": seg,
            "growth_bl": growth,
            "fac_share": (fac / growth) if growth > 0 else 0.0,
            "providers": cell_src["providers"],
            "placed_bl": cell_src["placed_bl"],
            "borrowed_bl": cell_src["borrowed"],
            "unplaced_bl": float(r.unplaced_cnt or 0),
            "h": _h_rate.get((cty, ctg), {}).get("h", _h_global_med)
                 if ctg else _h_global_med,
        })
        for p in cell_src["providers"]:
            b = _budget.get((p["pid"], p["county"]))
            if b and p["pid"] not in store["providers"]:
                store["providers"][p["pid"]] = {
                    "budget": b["budget"], "util_now": b["util_now"],
                    "spec": b["spec"], "county": p["county"]}
    print(f"[county-risk] precompute done: {len(CAP_STORE):,} counties in "
          f"store", flush=True)


def _seg_scale(seg, bands):
    if seg is None:
        return 0.0
    if seg.endswith("60_74"):
        return (bands[0] + bands[1]) / 2.0
    return (bands[2] + bands[3]) / 2.0


def cap_refill(county, bands):
    """Simplified module-69 mirror: facility peel, then per county x spec
    (NEW segments before RET) a two-pass proportional deal against provider
    count-caps = remaining budget hours / h (DASH-A1)."""
    store = CAP_STORE.get(county)
    if not store:
        return None
    cap_rem = {pid: (p["budget"] / 1.0) for pid, p in store["providers"].items()}
    for pid, p in store["providers"].items():
        h = _h_global_med
        for cell in store["cells"]:
            if cell["ctg"] == p["spec"]:
                h = cell["h"]
                break
        cap_rem[pid] = p["budget"] / max(h, 0.1)
    cells_out = []
    ordered = sorted(store["cells"],
                     key=lambda c: (c["seg"] is None,
                                    not (c["seg"] or "").startswith("NEW")))
    for cell in ordered:
        scale = 1.0 + _seg_scale(cell["seg"], bands) / 100.0
        growth = cell["growth_bl"] * max(scale, 0.0)
        fac = growth * cell["fac_share"]
        ind = growth - fac
        provs = [p for p in cell["providers"] if p["share"] > 0]
        placed = 0.0
        alloc = {}
        if provs and ind > 0:
            pool = 0.0
            for p in provs:
                p1 = ind * p["share"]
                take = min(p1, max(cap_rem.get(p["pid"], 0.0), 0.0))
                alloc[p["pid"]] = take
                cap_rem[p["pid"]] = cap_rem.get(p["pid"], 0.0) - take
                pool += p1 - take
            room = {p["pid"]: max(cap_rem.get(p["pid"], 0.0), 0.0)
                    for p in provs}
            room_total = sum(room.values())
            if pool > 0 and room_total > 0:
                deal = min(1.0, pool / room_total)
                for p in provs:
                    extra = room[p["pid"]] * deal
                    alloc[p["pid"]] = alloc.get(p["pid"], 0.0) + extra
                    cap_rem[p["pid"]] -= extra
                pool = max(pool - room_total, 0.0)
            placed = sum(alloc.values())
        unplaced = max(growth - fac - placed, 0.0)
        cells_out.append({**cell, "growth": growth, "fac": fac,
                          "placed": placed, "unplaced": unplaced,
                          "alloc": alloc})
    return {"cells": cells_out, "cap_rem": cap_rem, "store": store}


def cap_county_rows(state, bands, sort_key, show_unattributed):
    rows = []
    for cty, store in CAP_STORE.items():
        if state != "All" and store["state"] != state:
            continue
        result = cap_refill(cty, bands)
        if not result:
            continue
        cells = result["cells"]
        if not show_unattributed:
            cells = [c for c in cells if c["cms"] and c["seg"]]
        growth = sum(c["growth"] for c in cells)
        placed = sum(c["placed"] for c in cells)
        fac = sum(c["fac"] for c in cells)
        unplaced = sum(c["unplaced"] for c in cells)
        over_now = sum(1 for p in result["store"]["providers"].values()
                       if (p["util_now"] or 0) >= 1.0)
        over_after = sum(
            1 for pid, p in result["store"]["providers"].items()
            if (p["util_now"] or 0) >= 1.0 or result["cap_rem"].get(pid, 0) <= 1e-9)
        current = BASE_VISITS_TOTAL.get(cty, 0.0)
        rows.append({
            "_cty": cty, "_unplaced": unplaced, "_over": over_after,
            "county": county_label(cty),
            "current_visits": fmt(current),
            "visits_after_growth": fmt(current + placed + fac),
            "unplaced_risk": fmt(unplaced),
            "over_line_now_after": f"{over_now} / {over_after}",
            "facility_share": (f"{fac / growth:.0%}" if growth > 0 else "-"),
            "_unplaced_pct": (unplaced / growth) if growth > 0 else 0.0,
        })
    key = "_over" if sort_key == "over" else "_unplaced"
    return sorted(rows, key=lambda r: -r[key])


CAP_FLOW_STAGES = [
    (1, "Observed work — every visit we can see.", ACCENT_DATA,
     "Aetna MA claims (day grain) plus the CMS FFS public file (annual, "
     "one row per provider) — module 61."),
    (2, "Minutes per service.", ACCENT_DATA,
     "The CMS physician work-time file gives intra-service minutes per "
     "procedure code; unmatched codes get zero minutes by design — "
     "modules 60/62."),
    (3, "Calibration — every tuning number solved, none hard-coded.", ACCENT_MODEL,
     "Deflation, the daily cap, benchmark percentile, cohort sizes and "
     "the blending constant are solved and stored in one table (cap_params) "
     "— module 63."),
    (4, "The feasible day.", ACCENT_MODEL,
     "Hours are deflated, capped at the calibrated daily maximum; "
     "over-cap hours are kept separately as team uplift — module 64."),
    (5, "Ceiling — what a full year could hold.", ACCENT_MODEL,
     "Peer benchmark rate x the provider's own working days = ceiling; "
     "spare = ceiling minus observed — module 65."),
    (6, "Patient-type matrix.", ACCENT_MODEL,
     "8 patient types (new/returning x chronic x age). Each provider's "
     "intake per type, credibility-blended with peers; OWN vs BORROWED "
     "tagged — modules 66/67."),
    (7, "Two-lane fill.", NEUTRAL_BOX,
     "Growth demand splits by patient type; facilities keep their share; "
     "NEW patients deal against intake caps, RETURNING against remaining "
     "room — modules 68/69."),
    (8, "County risk — who cannot be placed.", NEUTRAL_BOX,
     "Whatever no provider could absorb = unplaced = the risk number, by "
     "county, specialty and patient type — modules 70/71, validated by 72."),
]


def flows_section():
    demand_col = html.Div(style={"flex": "1", "minWidth": "460px"},
                          children=[flow_tab()])
    cap_children = [
        html.H3("How the capacity numbers flow (v2)"),
        html.Div("Reconstructed 8-step summary of modules 59-72 (DASH-1 "
                 "spec pending confirmation).",
                 style={"fontSize": "12px", "color": "#52514e",
                        "marginBottom": "12px"}),
    ]
    for i, (num, title, color, source) in enumerate(CAP_FLOW_STAGES):
        cap_children.append(stage_box(num, title, source, color))
        if i < len(CAP_FLOW_STAGES) - 1:
            cap_children.append(arrow())
    cap_col = html.Div(cap_children,
                       style={"flex": "1", "minWidth": "460px",
                              "padding": "12px"})
    return html.Div(style={"display": "flex", "gap": "24px",
                           "flexWrap": "wrap"},
                    children=[demand_col, cap_col])


def _county_geojson():
    d = _extract_dir()
    path = os.path.join(d, "geojson-counties-fips.json")
    try:
        if not os.path.isfile(path):
            url = ("https://raw.githubusercontent.com/plotly/datasets/"
                   "master/geojson-counties-fips.json")
            with _urlreq.urlopen(url, timeout=8) as resp:
                data = resp.read()
            with open(path, "wb") as f:
                f.write(data)
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


COUNTY_GEOJSON = _county_geojson() if CAP_ERROR is None else None


def cap_map_figure(rows):
    if COUNTY_GEOJSON is None:
        items = [(r["county"], 0.0, r["_unplaced_pct"]) for r in rows[:20]]
        fig = go.Figure(go.Bar(
            y=[r["county"] for r in rows[:20]],
            x=[r["_unplaced_pct"] for r in rows[:20]],
            orientation="h", marker_color="#b91c1c"))
        fig.update_layout(
            title={"text": "Unplaced % by county (map fallback - county "
                           "geojson unavailable offline)", "font": {"size": 13}},
            height=90 + 24 * max(len(rows[:20]), 1),
            margin={"l": 10, "r": 10, "t": 40, "b": 20},
            yaxis={"autorange": "reversed"},
            plot_bgcolor="#fcfcfb", paper_bgcolor="#fcfcfb")
        return fig
    fips = [str(r["_cty"]).zfill(5) for r in rows]
    vals = [round(r["_unplaced_pct"] * 100, 1) for r in rows]
    fig = go.Figure(go.Choropleth(
        geojson=COUNTY_GEOJSON, locations=fips, z=vals,
        colorscale=RED_SCALE, zmin=0,
        zmax=max(vals) if vals else 1,
        marker_line_color="#ffffff", marker_line_width=0.4,
        colorbar={"title": "unplaced %", "thickness": 12}))
    fig.update_geos(fitbounds="locations", visible=False)
    fig.update_layout(height=420,
                      margin={"l": 0, "r": 0, "t": 10, "b": 0},
                      paper_bgcolor="#fcfcfb")
    return fig


def county_risk_tab():
    if CAP_ERROR is not None:
        return html.Div(style={"padding": "24px"}, children=[
            html.H3("County Risk"),
            html.Div(f"Capacity v2 tables unavailable at startup: "
                     f"{CAP_ERROR}. Start the dashboard with BigQuery access "
                     f"(modules 59-71 must have run) to enable this tab.",
                     style={"background": "rgba(208,59,59,0.12)",
                            "border": "1px solid #d03b3b",
                            "borderRadius": "10px", "padding": "14px",
                            "maxWidth": "760px", "fontSize": "13px"}),
        ])
    return html.Div(children=[
        html.Div(style={"display": "flex", "gap": "16px",
                        "alignItems": "center", "marginBottom": "10px",
                        "flexWrap": "wrap"},
                 children=[
                     html.Div(style={"minWidth": "120px"}, children=[
                         dcc.Dropdown(id="cr-state",
                                      options=(["All"] + list(CAP_STATES)),
                                      value=(DEFAULT_STATE
                                             if DEFAULT_STATE in CAP_STATES
                                             else "All"),
                                      clearable=False)]),
                     dcc.RadioItems(
                         id="cr-sort",
                         options=[{"label": "Sort: total unplaced visits",
                                   "value": "unplaced"},
                                  {"label": "Sort: providers over capacity",
                                   "value": "over"}],
                         value="unplaced", inline=True,
                         style={"fontSize": "13px"},
                         inputStyle={"marginRight": "4px"},
                         labelStyle={"marginRight": "16px"}),
                     dcc.Checklist(
                         id="cr-unattributed",
                         options=[{"label": " show Unattributed rows "
                                            "(NULL segment/specialty)",
                                   "value": "show"}],
                         value=[], style={"fontSize": "13px"}),
                 ]),
        html.Div(style={"background": "#fcfcfb",
                        "border": "1px solid rgba(11,11,11,0.10)",
                        "borderRadius": "10px", "padding": "10px 14px",
                        "marginBottom": "12px"},
                 children=[
                     html.Div("Growth sliders (shared with the Simulator "
                              "tab - moving either set moves both)",
                              style={"fontSize": "12px", "fontWeight": "600",
                                     "marginBottom": "6px"}),
                     html.Div(style={"display": "flex", "gap": "18px",
                                     "flexWrap": "wrap"},
                              children=[
                                  html.Div(style={"flex": "1",
                                                  "minWidth": "180px"},
                                           children=[
                                      html.Label(f"Band {BAND_NAMES[i]} (%)",
                                                 style={"fontSize": "12px"}),
                                      dcc.Slider(id=f"crs-b{i}", min=-30,
                                                 max=100, step=0.25, value=0,
                                                 marks=slider_marks(-30, 100),
                                                 tooltip={"placement":
                                                          "bottom"})])
                                  for i in range(len(BANDS))]),
                 ]),
        html.Div(style={"display": "flex", "gap": "16px",
                        "alignItems": "flex-start", "flexWrap": "wrap"},
                 children=[
                     html.Div(style={"flex": "1.2", "minWidth": "520px"},
                              children=[
                                  dash_table.DataTable(
                                      id="cr-table",
                                      columns=[{"name": n, "id": i} for n, i in [
                                          ("county", "county"),
                                          ("current visits",
                                           "current_visits"),
                                          ("visits after growth",
                                           "visits_after_growth"),
                                          ("unplaced (risk)",
                                           "unplaced_risk"),
                                          ("providers over line now / after",
                                           "over_line_now_after"),
                                          ("facility share",
                                           "facility_share")]],
                                      row_selectable=False,
                                      **TABLE_STYLE)]),
                     html.Div(style={"flex": "1", "minWidth": "420px"},
                              children=[
                                  dcc.Graph(id="cr-map",
                                            config={"displayModeBar": False}),
                                  html.Div("Map is display-only; click a "
                                           "table row for county detail.",
                                           style={"fontSize": "11px",
                                                  "color": "#898781"})]),
                 ]),
        html.Div(id="cr-detail", style={"marginTop": "14px"}),
    ])


app.layout = html.Div(
    style={"maxWidth": "1200px", "margin": "0 auto", "padding": "16px",
           "fontFamily": "system-ui, sans-serif"},
    children=[
        dcc.Store(id="store-sync", data=None),
        dcc.Store(id="store-county", data=None),
        html.Div("MVP - baseline anchored to 2025 actual visits; capacity "
                 "is a v0 placeholder (observed peak). Directional tool.",
                 style={"background": "#fab219", "color": "#0b0b0b",
                        "fontWeight": "700", "textAlign": "center",
                        "padding": "8px", "borderRadius": "8px",
                        "marginBottom": "4px", "letterSpacing": "0.02em"}),
        html.Div(MANIFEST_LINE,
                 style={"fontSize": "11px", "color": "#52514e",
                        "textAlign": "center", "marginBottom": "2px"}),
        html.Div(f"Capacity v2 pipeline (modules 59-72), {CAP_LOADED_DATE}, "
                 f"scenario-driven — magnitudes reflect slider settings.",
                 style={"fontSize": "11px", "color": "#52514e",
                        "textAlign": "center", "marginBottom": "12px"}),
        dcc.Tabs(value="tab-sim", children=[
            dcc.Tab(label="Simulator", value="tab-sim",
                    children=[simulator_tab()]),
            dcc.Tab(label="County Risk", value="tab-risk",
                    children=[county_risk_tab()]),
            dcc.Tab(label="How the numbers flow", value="tab-flow",
                    children=[flows_section()]),
            dcc.Tab(label="How it works", value="tab-method",
                    children=[methodology_tab()]),
            dcc.Tab(label="Model details", value="tab-model",
                    children=[model_tab()]),
        ]),
    ])


def build_hbar_figure(title, items):
    fig = go.Figure()
    n = len(items)
    y = list(range(n))
    names, base_seg, grow_seg, labels, dash_x, dash_y = [], [], [], [], [], []
    max_x = 1.0
    for i, (name, base, scen) in enumerate(items):
        delta = scen - base
        names.append(name)
        if scen >= base:
            base_seg.append(base)
            grow_seg.append(delta)
        else:
            base_seg.append(scen)
            grow_seg.append(0)
            dash_x.extend([base, base, None])
            dash_y.extend([i - 0.35, i + 0.35, None])
        labels.append(f"{fmt(scen)} ({delta:+,.0f})")
        max_x = max(max_x, base, scen)
    fig.add_trace(go.Bar(y=y, x=base_seg, orientation="h",
                         marker_color=GRAY, name="Baseline"))
    fig.add_trace(go.Bar(y=y, x=grow_seg, orientation="h",
                         marker_color=GREEN, name="Growth"))
    if dash_x:
        fig.add_trace(go.Scatter(x=dash_x, y=dash_y, mode="lines",
                                 line={"color": "#52514e", "dash": "dash",
                                       "width": 2},
                                 name="Baseline level"))
    for i, (name, base, scen) in enumerate(items):
        fig.add_annotation(x=max(base, scen), y=i, text=labels[i],
                           showarrow=False, xanchor="left", xshift=6,
                           font={"size": 11})
    fig.update_layout(barmode="stack",
                      height=90 + 34 * max(n, 1),
                      margin={"l": 10, "r": 10, "t": 40, "b": 30},
                      title={"text": title, "font": {"size": 14}},
                      yaxis={"tickvals": y, "ticktext": names,
                             "autorange": "reversed"},
                      xaxis={"range": [0, max_x * 1.28]},
                      legend={"orientation": "h", "y": -0.18},
                      plot_bgcolor="#fcfcfb", paper_bgcolor="#fcfcfb")
    return fig


@app.callback(
    Output("dd-county", "options"),
    Output("dd-county", "value"),
    Input("dd-state", "value"),
)
def select_state(state):
    counties = state_counties(state or DEFAULT_STATE)
    options = [{"label": county_label(c), "value": c} for c in counties]
    return options, (counties[0] if counties else None)


@app.callback(
    Output("store-county", "data"),
    Output("i-master", "children"),
    Output("i-b0", "children"),
    Output("i-b1", "children"),
    Output("i-b2", "children"),
    Output("i-b3", "children"),
    Input("dd-county", "value"),
)
def select_county(county):
    if not county:
        raise PreventUpdate
    payload = county_payload(county)
    return (payload, payload["master_label"], payload["labels"][0],
            payload["labels"][1], payload["labels"][2], payload["labels"][3])


@app.callback(
    Output("lbl-coef-base", "children"),
    Output("fig-coef", "figure"),
    Output("tbl-coef", "data"),
    Input("dd-coef-spec", "value"),
)
def coef_explorer(spec):
    spec = spec or SPECIALTIES[0]
    base = BASE_RATE.get(spec, 0.0)
    base_line = (f"Base visits per member (everyone, before conditions): "
                 f"{base:.2f}")
    rows = RATES[(RATES["cms_specialty"] == spec)
                 & (~RATES["condition"].isin(["BASE_RATE"]))]
    rows = rows.sort_values("visit_rate", ascending=False)
    top = rows.head(15)
    names = [cond_label(str(c)) if c != "OTHER_CONDITION"
             else "Other conditions (pooled)" for c in top["condition"]]
    fig = go.Figure(go.Bar(
        y=list(range(len(top))), x=list(top["visit_rate"]),
        orientation="h", marker_color=GREEN))
    fig.update_layout(
        height=90 + 30 * max(len(top), 1),
        margin={"l": 10, "r": 10, "t": 40, "b": 30},
        title={"text": f"{spec}: top condition visit rates",
               "font": {"size": 14}},
        yaxis={"tickvals": list(range(len(top))), "ticktext": names,
               "autorange": "reversed"},
        plot_bgcolor="#fcfcfb", paper_bgcolor="#fcfcfb")
    table = [{"condition": ("Other conditions (pooled)"
                            if str(r.condition) == "OTHER_CONDITION"
                            else cond_label(str(r.condition))),
              "visit_rate": f"{float(r.visit_rate):.3f}",
              "members_with_condition": fmt(r.members_with_condition)}
             for r in rows.itertuples()]
    return base_line, fig, table


@app.callback(
    Output("s-master", "value"),
    Output("s-b0", "value"),
    Output("s-b1", "value"),
    Output("s-b2", "value"),
    Output("s-b3", "value"),
    Output("store-sync", "data"),
    Output("r-master", "children"),
    Output("r-b0", "children"),
    Output("r-b1", "children"),
    Output("r-b2", "children"),
    Output("r-b3", "children"),
    Output("k-enroll", "children"),
    Output("k-visits", "children"),
    Output("k-at", "children"),
    Output("k-over", "children"),
    Output("tbl-enroll", "data"),
    Output("tbl-condition", "data"),
    Output("fig-specialty", "figure"),
    Output("fig-condition", "figure"),
    Output("tbl-demand", "data"),
    Output("tbl-provider", "data"),
    Output("lbl-provider-note", "children"),
    Input("s-master", "value"),
    Input("s-b0", "value"),
    Input("s-b1", "value"),
    Input("s-b2", "value"),
    Input("s-b3", "value"),
    Input("btn-reset", "n_clicks"),
    Input("dd-specialty", "value"),
    Input("rad-topn", "value"),
    Input("store-county", "data"),
    State("store-sync", "data"),
)
def update(master, b0, b1, b2, b3, _reset_clicks, selected_specialties,
           top_n, payload, sync_token):
    if not payload:
        raise PreventUpdate
    trigger = ctx.triggered_id
    master = master if master is not None else MASTER_DEFAULT
    bands = [v if v is not None else BAND_DEFAULTS[i]
             for i, v in enumerate([b0, b1, b2, b3])]

    slider_out = [no_update] * 5
    store_out = no_update
    if trigger == "btn-reset":
        bands = list(BAND_DEFAULTS)
        slider_out = [MASTER_DEFAULT] + list(BAND_DEFAULTS)
        store_out = MASTER_DEFAULT if master != MASTER_DEFAULT else None
    elif trigger == "s-master":
        if sync_token is not None and master == sync_token:
            store_out = None
        else:
            bands = [master] * len(BANDS)
            slider_out = [no_update] + [master] * len(BANDS)
            store_out = None

    base_members = payload["members"]
    prev = payload["prev"]
    other_prev = payload["other_prev"]
    cal = payload["cal"]
    base_demand = payload["base_demand"]
    base_conditions = payload["base_conditions"]
    base_other = payload["base_other"]
    base_ranks = payload["base_ranks"]

    members = [max(0.0, base_members[i] * (1 + bands[i] / 100.0))
               for i in range(len(BANDS))]
    demand, cond_now, other_now = compute_demand(members, prev, other_prev,
                                                 cal)
    deltas = {s: demand[s] - base_demand.get(s, 0.0) for s in SPECIALTIES}

    total_enroll = sum(members)
    total_base = sum(base_members)
    readout_master = (
        f"Total: {fmt(total_enroll)} members "
        f"({pct((total_enroll - total_base) / total_base) if total_base else 'n/a'} vs baseline)")
    readouts = [f"{BAND_NAMES[i]}: {bands[i]:+.2f}% -> {fmt(members[i])} "
                f"members" for i in range(len(BANDS))]

    enroll_rows = []
    for i, band in enumerate(BAND_NAMES):
        base = base_members[i]
        d = members[i] - base
        enroll_rows.append({
            "band": band, "baseline": fmt(base), "scenario": fmt(members[i]),
            "delta": f"{d:+,.0f}",
            "pct_change": pct(d / base) if base else "n/a"})

    n_show = top_n if top_n is not None else 10
    order, cur_ranks = ranks_desc(cond_now)
    condition_rows = []
    for pos, c in enumerate(order[:n_show]):
        base_c = base_conditions.get(c, 0.0)
        d = cond_now[c] - base_c
        moved = base_ranks.get(c, cur_ranks[c]) - cur_ranks[c]
        if moved > 0:
            movement = f"^{moved}"
        elif moved < 0:
            movement = f"v{-moved}"
        else:
            movement = "-"
        condition_rows.append({
            "rank": pos + 1,
            "movement": movement,
            "condition": cond_label(c),
            "baseline_members": fmt(base_c),
            "scenario_members": fmt(cond_now[c]),
            "delta": f"{d:+,.0f}",
            "pct_change": pct(d / base_c) if base_c else "n/a"})
    rest = order[n_show:]
    if rest:
        rest_base = sum(base_conditions.get(c, 0.0) for c in rest)
        rest_now = sum(cond_now[c] for c in rest)
        condition_rows.append({
            "rank": "", "movement": "",
            "condition": f"Other listed ({len(rest)} conditions)",
            "baseline_members": fmt(rest_base),
            "scenario_members": fmt(rest_now),
            "delta": f"{rest_now - rest_base:+,.0f}",
            "pct_change": ""})
    condition_rows.append({
        "rank": "", "movement": "",
        "condition": "Other conditions (pooled)",
        "baseline_members": fmt(base_other),
        "scenario_members": fmt(other_now),
        "delta": f"{other_now - base_other:+,.0f}",
        "pct_change": (pct((other_now - base_other) / base_other)
                       if base_other else "")})

    selected = set(selected_specialties or [])
    demand_rows = []
    for s in SPECIALTIES:
        if s not in selected:
            continue
        base_s = base_demand.get(s, 0.0)
        demand_rows.append({
            "specialty": s, "baseline_visits": fmt(base_s),
            "scenario_visits": fmt(demand[s]),
            "delta": f"{deltas[s]:+,.0f}",
            "pct_change": pct(deltas[s] / base_s) if base_s else "n/a"})

    n_at = 0
    n_over = 0
    no_weight = 0
    provider_rows = []
    for p in payload["providers"]:
        w = p["weight"]
        if w is None:
            no_weight += 1
            new_demand = None
        else:
            new_demand = deltas.get(p["spec"], 0.0) * w
        load = p["visits"] + (new_demand or 0.0)
        utilization = load / p["ceiling"] if p["ceiling"] else 0.0
        status = status_of(utilization)
        if status == "AT CAPACITY":
            n_at += 1
        if status == "OVER CAPACITY":
            n_over += 1
        if p["spec"] in selected:
            room = p["ceiling"] - load
            provider_rows.append({
                "_visits": p["visits"],
                "provider": p["id"], "specialty": p["spec"],
                "current_visits": fmt(p["visits"]),
                "estimated_max": f"~{fmt(p['ceiling'])}",
                "new_demand_coming": (f"{new_demand:+,.0f}"
                                      if new_demand is not None else "-"),
                "room_left": (fmt(room) if room >= 0
                              else f"short by {fmt(-room)}"),
                "status": status})
    total_in_selection = len(provider_rows)
    provider_rows = sorted(provider_rows,
                           key=lambda r: -r["_visits"])[:TOP_PROVIDERS_SHOWN]
    for r in provider_rows:
        r.pop("_visits", None)
    note = (f"{payload['prov_mode']}; showing top {len(provider_rows)} of "
            f"{total_in_selection} in selection by 2025 visits; "
            f"{no_weight} carry no intake weight (unknown state or zero "
            f"2025 new-patient visits in their cell - excluded from "
            f"routing)")

    spec_items = sorted(
        ((s, base_demand.get(s, 0.0), demand[s])
         for s in SPECIALTIES if s in selected),
        key=lambda t: -t[2])[:n_show]
    cond_items = [(cond_label(c), base_conditions.get(c, 0.0), cond_now[c])
                  for c in order[:n_show]]
    fig_specialty = build_hbar_figure(
        f"Specialty demand - top {n_show}", spec_items)
    fig_condition = build_hbar_figure(
        f"Condition members - top {n_show}", cond_items)

    return (slider_out[0], slider_out[1], slider_out[2], slider_out[3],
            slider_out[4], store_out,
            readout_master, readouts[0], readouts[1], readouts[2],
            readouts[3],
            fmt(total_enroll), fmt(sum(demand.values())), str(n_at),
            str(n_over),
            enroll_rows, condition_rows, fig_specialty, fig_condition,
            demand_rows, provider_rows, note)


if CAP_ERROR is None:

    @app.callback(
        [Output(f"crs-b{i}", "value") for i in range(len(BANDS))],
        [Input(f"s-b{i}", "value") for i in range(len(BANDS))],
        [State(f"crs-b{i}", "value") for i in range(len(BANDS))],
        prevent_initial_call=True,
    )
    def sync_sliders_to_risk(*vals):
        src = [v if v is not None else 0 for v in vals[:len(BANDS)]]
        cur = [v if v is not None else 0 for v in vals[len(BANDS):]]
        if src == cur:
            raise PreventUpdate
        return src

    @app.callback(
        [Output(f"s-b{i}", "value", allow_duplicate=True)
         for i in range(len(BANDS))],
        [Input(f"crs-b{i}", "value") for i in range(len(BANDS))],
        [State(f"s-b{i}", "value") for i in range(len(BANDS))],
        prevent_initial_call=True,
    )
    def sync_sliders_from_risk(*vals):
        src = [v if v is not None else 0 for v in vals[:len(BANDS)]]
        cur = [v if v is not None else 0 for v in vals[len(BANDS):]]
        if src == cur:
            raise PreventUpdate
        return src

    @app.callback(
        Output("cr-table", "data"),
        Output("cr-map", "figure"),
        Output("cr-detail", "children"),
        Input("cr-state", "value"),
        Input("cr-sort", "value"),
        Input("cr-unattributed", "value"),
        [Input(f"s-b{i}", "value") for i in range(len(BANDS))],
        Input("cr-table", "active_cell"),
        State("cr-table", "data"),
    )
    def update_county_risk(state, sort_key, unattributed, b0, b1, b2, b3,
                           active_cell, prev_data):
        bands = [v if v is not None else 0 for v in (b0, b1, b2, b3)]
        show_unattr = "show" in (unattributed or [])
        rows = cap_county_rows(state or "All", bands, sort_key or "unplaced",
                               show_unattr)
        fig = cap_map_figure(rows)

        detail = html.Div("Click a county row for detail.",
                          style={"fontSize": "12px", "color": "#898781"})
        source = prev_data if ctx.triggered_id == "cr-table" else rows
        if active_cell and source and active_cell["row"] < len(source):
            cty = source[active_cell["row"]].get("_cty")
            result = cap_refill(cty, bands) if cty else None
            if result:
                seg_agg = {s: {"growth": 0.0, "unplaced": 0.0}
                           for s in SEGMENTS_8}
                growth_t = fac_t = placed_t = borrowed_t = placed_bl_t = 0.0
                for c in result["cells"]:
                    growth_t += c["growth"]
                    fac_t += c["fac"]
                    placed_t += c["placed"]
                    borrowed_t += c["borrowed_bl"]
                    placed_bl_t += c["placed_bl"]
                    if c["seg"] in seg_agg:
                        seg_agg[c["seg"]]["growth"] += c["growth"]
                        seg_agg[c["seg"]]["unplaced"] += c["unplaced"]
                seg_rows = [{"patient_type": s,
                             "growth": fmt(seg_agg[s]["growth"]),
                             "unplaced": fmt(seg_agg[s]["unplaced"])}
                            for s in SEGMENTS_8]
                top5 = sorted(result["cap_rem"].items(),
                              key=lambda kv: -kv[1])[:5]
                prov_rows = [{"provider": pid,
                              "specialty": result["store"]["providers"]
                              .get(pid, {}).get("spec", ""),
                              "remaining_room_visits": fmt(max(room, 0))}
                             for pid, room in top5]
                detail = html.Div(
                    style={"background": "#fcfcfb",
                           "border": "1px solid rgba(11,11,11,0.10)",
                           "borderRadius": "10px", "padding": "14px"},
                    children=[
                        html.H4(f"County detail: {county_label(cty)}"),
                        html.Div(style={"display": "flex", "gap": "24px",
                                        "flexWrap": "wrap"},
                                 children=[
                            html.Div(style={"flex": "1", "minWidth": "300px"},
                                     children=[
                                html.Div("Unplaced by patient type",
                                         style={"fontWeight": "600",
                                                "fontSize": "13px",
                                                "marginBottom": "4px"}),
                                dash_table.DataTable(
                                    columns=[{"name": c, "id": c} for c in
                                             ["patient_type", "growth",
                                              "unplaced"]],
                                    data=seg_rows, **TABLE_STYLE)]),
                            html.Div(style={"flex": "1", "minWidth": "300px"},
                                     children=[
                                html.Div("Top 5 providers by remaining room",
                                         style={"fontWeight": "600",
                                                "fontSize": "13px",
                                                "marginBottom": "4px"}),
                                dash_table.DataTable(
                                    columns=[{"name": c, "id": c} for c in
                                             ["provider", "specialty",
                                              "remaining_room_visits"]],
                                    data=prov_rows, **TABLE_STYLE),
                                html.Div(
                                    f"Facility absorbed share: "
                                    f"{(fac_t / growth_t) if growth_t else 0:.0%} "
                                    f"| Borrowed-signal share of baseline "
                                    f"placements (honesty): "
                                    f"{(borrowed_t / placed_bl_t) if placed_bl_t else 0:.0%}",
                                    style={"fontSize": "12px",
                                           "marginTop": "8px"})]),
                        ]),
                    ])
        return rows, fig, detail


if __name__ == "__main__":
    print("[startup] starting server on :8051", flush=True)
    app.run(host="0.0.0.0", port=8051, debug=False)
