"""
whatif_dashboard_v2.py - v2: tabs, filters, methodology   [Plotly Dash]

v2 of the wired MVP dashboard (whatif_dashboard.py stays untouched).
Port 8051, proxy env var DASH_PROXY_PREFIX_V2, same proxy pattern.
Loads the EIGHT parquet extracts + manifest.json from ./extracts/ once
at startup; no file reads after startup. Tabs: (1) Simulator - state ->
county cascade with county names, OTHER_CONDITION term closed into the
demand bracket so baseline reproduces 2025 actuals exactly up to the
clamped calibration cells, name-matched provider table, collapsible
number tables, glossary hover text; (2) How the numbers flow - the
six-stage plain-language flow; (3) How it works - methodology, inputs,
assumptions, glossary; (4) Model details - coefficient explorer, fit
quality, evidence and freshness cards. Screen text says "local care
pattern" for the calibration factor; code and table names unchanged.
Demand cascade:
  demand[spec] = local_pattern[county, spec] x (
      sum_b members_b x BASE_RATE[spec]
    + sum_{b,c} members_b x prevalence[county, b, c] x rate[c, spec]
    + sum_b members_b x other_prevalence[county, b] x
      rate[OTHER_CONDITION, spec])
Run: python model_and_dashboard_v1/07_dashboard/whatif_dashboard_v2.py
Deps: dash, plotly, pandas, pyarrow. Extracts must be regenerated by
21_dashboard_extracts.py (eight-file set) before first launch.
"""

import json
import os

import pandas as pd
import plotly.graph_objects as go
from dash import Dash, Input, Output, State, ctx, dash_table, dcc, html, no_update
from dash.exceptions import PreventUpdate

BANDS = ["60-64", "65-74", "75-84", "85p"]
BAND_NAMES = ["60-64", "65-74", "75-84", "85+"]
MASTER_DEFAULT = 0
BAND_DEFAULTS = [0, 0, 0, 0]
TOP_PROVIDERS_SHOWN = 50
TOP_PROVIDERS_STORED_PER_SPEC = 50
DEFAULT_STATE = "FL"

GRAY = "#c3c2b7"
GREEN = "#0ca30c"
ACCENT_DATA = "#e8f4e8"
ACCENT_MODEL = "#e6eefb"
NEUTRAL_BOX = "#f4f4f2"

GLOSSARY = {
    "prevalence": "The share of members in a county and age group who "
                  "hold a condition, counted from 2025 claims.",
    "base rate": "Visits per member that everyone makes regardless of "
                 "conditions - the regression intercept.",
    "visit rate": "Extra visits per year that one condition adds in one "
                  "specialty - a fitted regression coefficient.",
    "local care pattern": "Actual 2025 visits divided by the formula's "
                          "2025 number, per county and specialty. Anchors "
                          "the baseline to local reality and resizes every "
                          "slider change to local behavior.",
    "intake weight": "The provider's share of last year's new patients "
                     "in their county and specialty - how new demand is "
                     "split among providers.",
    "ceiling": "v0 placeholder capacity: the provider's busiest observed "
               "month (2024-2025) times 12. A model replaces this later.",
    "headroom": "Ceiling minus load: how many more annual visits fit "
                "before the provider is at capacity.",
    "new demand": "The scenario's change in annual visits (delta) routed "
                  "to a provider via their intake weight.",
    "movement arrows": "^k / vk: the condition rose or fell k rank "
                       "positions versus baseline; - means unchanged.",
}


def _extract_dir():
    try:
        here = os.path.dirname(os.path.abspath(__file__))
    except NameError:
        here = os.getcwd()
    cand = os.path.join(here, "extracts")
    if os.path.isdir(cand):
        return cand
    probe = here
    for _ in range(6):
        cand = os.path.join(probe, "model_and_dashboard_v1", "07_dashboard",
                            "extracts")
        if os.path.isdir(cand):
            return cand
        probe = os.path.dirname(probe)
    raise FileNotFoundError(
        "extracts folder not found - run 21_dashboard_extracts.py first")


def load_extracts():
    d = _extract_dir()
    names = ["enrollment", "growth_context", "sickness_rates", "visit_rates",
             "county_calibration", "providers", "conditions_meta",
             "other_condition_prevalence"]
    frames = {}
    for n in names:
        path = os.path.join(d, f"{n}.parquet")
        if not os.path.isfile(path):
            raise FileNotFoundError(
                f"{n}.parquet missing - regenerate the eight-file extract "
                f"set with 21_dashboard_extracts.py")
        frames[n] = pd.read_parquet(path)
    with open(os.path.join(d, "manifest.json"), "r", encoding="utf-8") as f:
        manifest = json.load(f)
    return frames, manifest


FRAMES, MANIFEST = load_extracts()

ENR = FRAMES["enrollment"]
GROWTH = FRAMES["growth_context"]
SICK = FRAMES["sickness_rates"]
RATES = FRAMES["visit_rates"]
CAL = FRAMES["county_calibration"]
PROV = FRAMES["providers"]
META = FRAMES["conditions_meta"]
OTHER = FRAMES["other_condition_prevalence"]

COUNTY_STATE = dict(zip(ENR["mbr_county_cd"], ENR["state_cd"]))
COUNTY_MEMBERS = {
    cty: dict(zip(g["age_band"], g["members"]))
    for cty, g in ENR.groupby("mbr_county_cd")}
COUNTY_NAME = {}
if "county_name" in ENR.columns:
    COUNTY_NAME = dict(zip(ENR["mbr_county_cd"], ENR["county_name"]))
_county_totals = ENR.groupby("mbr_county_cd")["members"].sum()
STATES = sorted(set(COUNTY_STATE.values()))


def county_label(c):
    name = COUNTY_NAME.get(c)
    return f"{name} ({c})" if name else c


def state_counties(state):
    return sorted((c for c, s in COUNTY_STATE.items() if s == state),
                  key=lambda c: -_county_totals.get(c, 0))


def default_county(state):
    counties = state_counties(state)
    return counties[0] if counties else None


GROWTH_LOOKUP = {(r.mbr_county_cd, r.age_band): float(r.last_year_yoy_pct)
                 for r in GROWTH.itertuples()
                 if pd.notna(r.last_year_yoy_pct)}
_state_growth = GROWTH.dropna(subset=["last_year_yoy_pct"]) \
    .groupby(["state_cd", "age_band"])["last_year_yoy_pct"].mean()
STATE_GROWTH = {k: float(v) for k, v in _state_growth.items()}

SPECIALTIES = sorted(RATES["cms_specialty"].unique())
BASE_RATE = {r.cms_specialty: float(r.visit_rate)
             for r in RATES.itertuples() if r.condition == "BASE_RATE"}
OTHER_RATE = {r.cms_specialty: float(r.visit_rate)
              for r in RATES.itertuples()
              if r.condition == "OTHER_CONDITION"}
RATE_LOOKUP = {}
for r in RATES.itertuples():
    if r.condition in ("BASE_RATE", "OTHER_CONDITION"):
        continue
    if float(r.visit_rate) > 0:
        RATE_LOOKUP.setdefault(str(r.condition), {})[r.cms_specialty] = \
            float(r.visit_rate)

SPEC_R2 = {r.cms_specialty: (None if pd.isna(r.r2) else float(r.r2))
           for r in RATES.itertuples() if r.condition == "BASE_RATE"}
SPEC_DEFLATION = {}
if "deflation_factor" in RATES.columns:
    SPEC_DEFLATION = {
        r.cms_specialty: (None if pd.isna(r.deflation_factor)
                          else float(r.deflation_factor))
        for r in RATES.itertuples() if r.condition == "BASE_RATE"}

CAL_LOOKUP = {(r.mbr_county_cd, r.cms_specialty): float(r.calibration_factor)
              for r in CAL.itertuples()}

DESC = dict(zip(META["condition"].astype(str), META["description"]))

OTHER_PREV = {}
for r in OTHER.itertuples():
    key = r.mbr_county_cd
    if key not in OTHER_PREV:
        OTHER_PREV[key] = [0.0] * len(BANDS)
    if r.age_band in BANDS and pd.notna(r.other_prevalence):
        OTHER_PREV[key][BANDS.index(r.age_band)] = float(r.other_prevalence)


def _norm_county(name):
    n = str(name).upper().replace(".", "").strip()
    if n.startswith("SAINT "):
        n = "ST " + n[6:]
    return n


_names_states = {}
for _c, _n in COUNTY_NAME.items():
    _names_states.setdefault(_norm_county(_n), set()).add(
        COUNTY_STATE.get(_c))
NAME_COLLIDES = {k for k, v in _names_states.items() if len(v) > 1}


def growth_label(county, band):
    v = GROWTH_LOOKUP.get((county, band))
    if v is None:
        v = STATE_GROWTH.get((COUNTY_STATE.get(county), band))
    return f"last year: {v:+.1f}%" if v is not None else "last year: n/a"


def compute_demand(members_by_band, prev, other_prev, cal):
    total_members = sum(members_by_band)
    cond_members = {c: sum(members_by_band[b] * prev[c][b]
                           for b in range(len(BANDS)))
                    for c in prev}
    other_members = sum(members_by_band[b] * other_prev[b]
                        for b in range(len(BANDS)))
    demand = {}
    for s in SPECIALTIES:
        visits = total_members * BASE_RATE.get(s, 0.0)
        for c, n in cond_members.items():
            rate = RATE_LOOKUP.get(c, {}).get(s)
            if rate:
                visits += n * rate
        visits += other_members * OTHER_RATE.get(s, 0.0)
        demand[s] = cal.get(s, 1.0) * visits
    return demand, cond_members, other_members


def ranks_desc(values_by_key):
    order = sorted(values_by_key, key=lambda k: -values_by_key[k])
    return order, {k: pos + 1 for pos, k in enumerate(order)}


def county_payload(county):
    members = [int(COUNTY_MEMBERS.get(county, {}).get(b, 0)) for b in BANDS]
    labels = [growth_label(county, b) for b in BANDS]
    master_label = growth_label(county, "ALL_BANDS")

    slice_df = SICK[SICK["mbr_county_cd"] == county]
    prev = {}
    for r in slice_df.itertuples():
        cond = str(r.condition)
        if cond not in prev:
            prev[cond] = [0.0] * len(BANDS)
        if r.age_band in BANDS:
            prev[cond][BANDS.index(r.age_band)] = float(r.prevalence)
    other_prev = OTHER_PREV.get(county, [0.0] * len(BANDS))

    cal = {s: CAL_LOOKUP.get((county, s), 1.0) for s in SPECIALTIES}
    base_demand, base_conditions, base_other = compute_demand(
        members, prev, other_prev, cal)
    _, base_ranks = ranks_desc(base_conditions)

    name = COUNTY_NAME.get(county)
    matched = 0
    if name:
        target = _norm_county(name)
        prov = PROV[PROV["prvdr_county_clean"].map(
            lambda x: _norm_county(x) == target)]
        matched = len(prov)
    else:
        prov = PROV.iloc[0:0]
    if matched == 0:
        prov = PROV
        prov_mode = (f"0 providers matched to county "
                     f"{county_label(county)}; showing footprint-wide top "
                     f"providers (routing approximate)")
    else:
        prov_mode = (f"{matched:,} providers matched to "
                     f"{county_label(county)}")
        if target in NAME_COLLIDES:
            prov_mode += (" - NOTE: this county name exists in more than "
                          "one footprint state; provider rows and intake "
                          "weights pool those states until a provider "
                          "state column ships upstream")
    prov = prov.sort_values("visits_2025", ascending=False)
    prov = prov.groupby("cms_specialty", sort=False) \
               .head(TOP_PROVIDERS_STORED_PER_SPEC)
    providers = []
    for r in prov.itertuples():
        w = getattr(r, "intake_weight")
        providers.append({
            "id": str(r.epdb_dw_prvdr_id),
            "spec": r.cms_specialty,
            "visits": int(r.visits_2025),
            "ceiling": int(r.ceiling_annual_v0),
            "weight": None if pd.isna(w) else float(w),
        })

    return {
        "county": county,
        "members": members,
        "labels": labels,
        "master_label": master_label,
        "prev": prev,
        "other_prev": other_prev,
        "cal": cal,
        "base_demand": base_demand,
        "base_conditions": base_conditions,
        "base_other": base_other,
        "base_ranks": base_ranks,
        "providers": providers,
        "prov_mode": prov_mode,
    }


def fmt(n):
    return f"{n:,.0f}"


def pct(n):
    return f"{n:+.1%}"


def status_of(utilization):
    if utilization > 1.00:
        return "OVER CAPACITY"
    if utilization >= 0.90:
        return "AT CAPACITY"
    return "HEADROOM"


def cond_label(cond):
    desc = str(DESC.get(cond, "")).strip()
    return f"{desc[:40]} ({cond})" if desc else cond


def gloss(text, term):
    return html.Span(text, title=GLOSSARY.get(term, ""),
                     style={"textDecoration": "underline dotted",
                            "cursor": "help"})


TABLE_STYLE = {
    "style_table": {"overflowX": "auto"},
    "style_cell": {"fontFamily": "system-ui, sans-serif", "fontSize": "13px",
                   "padding": "6px 10px", "textAlign": "left"},
    "style_header": {"fontWeight": "600"},
}

PROXY_PREFIX = os.environ.get("DASH_PROXY_PREFIX_V2")
if PROXY_PREFIX:
    app = Dash(__name__, requests_pathname_prefix=PROXY_PREFIX)
else:
    app = Dash(__name__)

SCOPE_TEXT = [
    "Demographic changes move condition counts, and condition counts move "
    "specialty demand - that chain is the actual arithmetic of this page, "
    "not an illustration.",
    "With all sliders at 0 the page reproduces 2025 actual visit levels "
    "per county and specialty, up to three known residuals: the 45 cells "
    "where the local care pattern factor was clamped to the 0.1..3.0 "
    "range, small county cells whose prevalence is suppressed (under 30 "
    "members), and the difference between the December member snapshot "
    "used here and the full-year membership the factor was fitted on. "
    "Slider deltas are shaped by the fitted condition-to-specialty rates "
    "and resized by the local care pattern.",
    "Capacity is a v0 placeholder: each provider's ceiling is their own "
    "busiest observed month (2024-2025) times 12 - observed data, not a "
    "model - and it is Aetna-relative: only Aetna claims are visible, so a "
    "provider busy with other payers may look like they have room here "
    "when they do not.",
    "Routing assumes future patients choose providers the way past "
    "patients did: new demand flows in proportion to historical "
    "new-patient shares. Prevalence, visit rates and local care patterns "
    "are frozen during simulation; the sliders move enrollment only.",
    "This tool is directional, not a precise forecaster.",
]

MANIFEST_LINE = (f"extracts built {MANIFEST.get('built_at', 'n/a')} - "
                 f"{MANIFEST.get('note', '')}")


def kpi_tile(tile_id, label, term=None):
    label_el = gloss(label, term) if term else label
    return html.Div(style={"flex": "1", "minWidth": "170px",
                           "background": "#fcfcfb",
                           "border": "1px solid rgba(11,11,11,0.10)",
                           "borderRadius": "10px", "padding": "10px 14px"},
                    children=[
                        html.Div(label_el, style={"fontSize": "12px",
                                                  "color": "#52514e"}),
                        html.Div(id=tile_id,
                                 style={"fontSize": "24px",
                                        "fontWeight": "650"}),
                    ])


def slider_block(slider_id, readout_id, info_id, label, mn, mx, marks):
    return html.Div(style={"marginBottom": "16px"}, children=[
        html.Div(style={"display": "flex", "justifyContent": "space-between",
                        "alignItems": "baseline"},
                 children=[
                     html.Label(label, style={"fontSize": "13px",
                                              "fontWeight": "600"}),
                     html.Span(id=info_id,
                               title="Last year's actual December-to-"
                                     "December change - context only, never "
                                     "the starting position (D11).",
                               style={"fontSize": "11px",
                                      "color": "#2a78d6",
                                      "cursor": "help"}),
                 ]),
        dcc.Slider(id=slider_id, min=mn, max=mx, step=5, value=0,
                   marks=marks, tooltip={"placement": "bottom"}),
        html.Div(id=readout_id, style={"fontSize": "12px",
                                       "color": "#52514e"}),
    ])


def stage_box(number, title, source, color):
    return html.Div(style={"display": "flex", "gap": "16px",
                           "marginBottom": "4px"},
                    children=[
                        html.Div(style={"flex": "0 0 40%",
                                        "background": color,
                                        "border": "1px solid "
                                                  "rgba(11,11,11,0.12)",
                                        "borderRadius": "10px",
                                        "padding": "12px 16px"},
                                 children=[
                                     html.Div(f"{number}. {title}",
                                              style={"fontWeight": "650",
                                                     "fontSize": "14px"})]),
                        html.Div(source,
                                 style={"flex": "1", "fontSize": "13px",
                                        "color": "#3c3b38",
                                        "padding": "10px 4px"}),
                    ])


def arrow():
    return html.Div("↓", style={"textAlign": "left",
                                     "marginLeft": "18%",
                                     "fontSize": "20px",
                                     "color": "#898781",
                                     "margin": "2px 0 6px 18%"})


FLOW_STAGES = [
    (1, "Slider moves — your growth assumption.", NEUTRAL_BOX,
     "No data here — you set this. We tested predicting growth from "
     "history; last year's change pointed the wrong way, so the slider "
     "starts at 0 and we only show last year's change as a label."),
    (2, "New member counts per age group.", ACCENT_DATA,
     "Real enrollment: members per county per age group, counted from "
     "membership records (Dec 2025). The slider applies to these counts. "
     "Example: 1,000 members aged 85+, slider +10% = 100 new members."),
    (3, "Condition mix — people, not visits yet.", ACCENT_DATA,
     "From 2025 claims we counted, per county and age group, the share of "
     "members with each condition — the prevalence. New members x "
     "prevalence = new members with each condition. Example: 100 x 30% = "
     "30 new CKD members. This is the condition table."),
    (4, "Visits per specialty — what each condition adds.", ACCENT_MODEL,
     "The one fitted model. One row per member (1.58M, 2025): 56 yes/no "
     "condition flags -> visit counts per specialty (a visit = one member, "
     "one provider, one day). A regression per specialty gives the base "
     "visits everyone makes plus a coefficient per condition — those "
     "coefficients are the visit rates. Example: 30 CKD members x 2.8 = "
     "84 nephrology visits — the model's job ends at per-member visits; "
     "everything after is addition and a sharing rule."),
    (5, "Local care pattern — anchor to this county's reality.",
     ACCENT_DATA,
     "The formula uses national patterns; counties have local habits. Per "
     "county and specialty: actual 2025 visits divided by the formula's "
     "2025 number = the factor. Baseline matches reality exactly, and "
     "every slider change is resized to local behavior. Example: factor "
     "0.9 -> 84 becomes 76."),
    (6, "County demand per specialty — add everyone up.", NEUTRAL_BOX,
     "Each member's predicted visits are summed to the county total per "
     "specialty. No model here — just addition. This is the number on "
     "the demand charts."),
    (7, "Providers — who absorbs the change.", NEUTRAL_BOX,
     "A sharing rule, not a model: each provider takes a share of the new "
     "demand equal to their share of last year's new patients in that "
     "county and specialty (intake weight). That load is checked against "
     "their ceiling — currently v0: busiest observed month x 12. Modeling "
     "who patients actually choose is a future improvement, listed in "
     "assumptions."),
]


def flow_tab():
    children = [
        html.H3("How the numbers flow"),
        html.Div("Boxes: gray = you set it / what you see; green = counted "
                 "from data; blue = fitted model.",
                 style={"fontSize": "12px", "color": "#52514e",
                        "marginBottom": "12px"}),
    ]
    for i, (num, title, color, source) in enumerate(FLOW_STAGES):
        children.append(stage_box(num, title, source, color))
        if i < len(FLOW_STAGES) - 1:
            children.append(arrow())
    children.append(html.Div(
        style={"border": "2px solid rgba(11,11,11,0.25)",
               "borderRadius": "10px", "padding": "14px 18px",
               "marginTop": "18px", "background": "#fcfcfb",
               "maxWidth": "820px"},
        children=[
            html.Div("Worked example", style={"fontWeight": "650",
                                              "marginBottom": "6px"}),
            html.Div("100 new 85+ members -> x30% = 30 CKD members -> "
                     "x2.8 = 84 nephrology visits -> x0.9 local pattern = "
                     "76 shown.",
                     style={"fontSize": "13px"}),
        ]))
    return html.Div(children, style={"maxWidth": "980px", "padding": "12px"})


INPUTS_ROWS = [
    {"input": "enrollment", "source": "membership records (Dec 2025)",
     "plain_words": "how many members live in each county, by age group",
     "grain": "county x age group"},
    {"input": "sickness rates", "source": "2025 claims diagnoses",
     "plain_words": "share of members holding each condition",
     "grain": "county x age group x condition"},
    {"input": "visit rates", "source": "fitted regression (one per "
                                       "specialty)",
     "plain_words": "base visits everyone makes + extra visits each "
                    "condition adds",
     "grain": "specialty x condition"},
    {"input": "local care pattern", "source": "actual 2025 visits vs the "
                                              "formula's 2025 number",
     "plain_words": "how this county's real utilization compares to the "
                    "national pattern",
     "grain": "county x specialty"},
    {"input": "providers", "source": "2024-2025 claims per provider",
     "plain_words": "current visits, observed-peak ceiling (v0), share of "
                    "new patients",
     "grain": "provider"},
    {"input": "growth context", "source": "December-to-December enrollment "
                                          "change",
     "plain_words": "last year's change, shown as a label only",
     "grain": "county x age group"},
]


def methodology_tab():
    return html.Div(style={"maxWidth": "900px", "padding": "12px",
                           "fontSize": "14px"}, children=[
        html.H3("How it works"),
        html.H4("The demand formula"),
        html.P("In words: take the members in each age group, apply the "
               "growth sliders, work out how many hold each condition, "
               "multiply by what each condition adds in each specialty, "
               "add the base visits everyone makes, then resize the total "
               "to this county's local care pattern."),
        html.P("In symbols: demand[specialty] = local_pattern x ( members "
               "x base_rate + sum over conditions of members_with_condition "
               "x visit_rate + members_with_other_conditions x other_rate )."),
        html.P("Mini example: 100 new 85+ members, 30% CKD prevalence, "
               "2.8 nephrology visits per CKD member, local pattern 0.9: "
               "100 x 30% = 30 members; 30 x 2.8 = 84 visits; 84 x 0.9 = "
               "76 visits added to nephrology."),
        html.H4("Condition mix"),
        html.P("Members can hold several conditions at once, so the "
               "condition column does not sum to enrollment. Conditions "
               "outside the 56 modeled ones are pooled into 'Other "
               "conditions (pooled)' with their own prevalence and rate."),
        html.H4("The growth label"),
        html.P("Sliders start at 0 (decision D11): we tested predicting "
               "growth from history and last year's change pointed the "
               "wrong way (enrollment is decided at the annual enrollment "
               "period, effective January 1). Last year's change appears "
               "as a label beside each slider - context, never a "
               "starting position."),
        html.H4("Routing"),
        html.P("New demand in a specialty is split among that county's "
               "providers by intake weight - each provider's share of "
               "last year's new patients. Providers whose county and "
               "specialty saw no new patients last year carry no weight "
               "and receive no routed demand."),
        html.H4("Capacity - PLACEHOLDER"),
        html.P("Capacity is v0: a provider's ceiling is their own busiest "
               "observed month (2024-2025) times 12. It is observed data, "
               "not a model, and it is Aetna-relative. The modeled "
               "ceiling (notebooks 16-18) replaces it in a later phase."),
        html.H4("Status definitions"),
        html.P("Load = current visits + new demand. Under 90% of ceiling "
               "= HEADROOM; 90-100% = AT CAPACITY; over 100% = OVER "
               "CAPACITY, shown as 'short by N'."),
        html.H4("Inputs"),
        dash_table.DataTable(
            columns=[{"name": c, "id": c} for c in
                     ["input", "source", "plain_words", "grain"]],
            data=INPUTS_ROWS, **TABLE_STYLE),
        html.H4("Assumptions"),
        html.P("Rates are frozen during simulation - the sliders move "
               "enrollment only. Capacity is Aetna-relative. Routing "
               "assumes past choice behavior. Conditions come from 2025 "
               "diagnoses, so first-year members can under-show "
               "conditions. Only CMS physician specialties are covered, "
               "by deliberate mapping policy. The local care pattern is "
               "fixed at its 2025 value."),
        html.H4("Glossary"),
        html.Div([html.Div([html.B(term.title()), html.Span(f" - {text}")],
                           style={"marginBottom": "6px"})
                  for term, text in GLOSSARY.items()],
                 style={"fontSize": "13px"}),
    ])


_cond_footprint = SICK.groupby(SICK["condition"].astype(str))[
    "members_with_condition"].sum()
_other_footprint = float(OTHER["members_with_other"].sum())
_total_members = float(ENR["members"].sum())


def base_rate_share(spec):
    base_v = _total_members * BASE_RATE.get(spec, 0.0)
    cond_v = sum(float(_cond_footprint.get(c, 0.0)) * r[spec]
                 for c, r in RATE_LOOKUP.items() if spec in r)
    cond_v += _other_footprint * OTHER_RATE.get(spec, 0.0)
    total = base_v + cond_v
    return base_v / total if total else None


FIT_ROWS = []
for s in SPECIALTIES:
    r2 = SPEC_R2.get(s)
    share = base_rate_share(s)
    defl = SPEC_DEFLATION.get(s)
    FIT_ROWS.append({
        "specialty": s,
        "r2": "n/a" if r2 is None else f"{r2:.3f}",
        "base_rate_share": "n/a" if share is None else f"{share:.0%}",
        "deflation_factor": "n/a" if defl is None else f"{defl:.3f}",
    })


def model_tab():
    return html.Div(style={"maxWidth": "980px", "padding": "12px"},
                    children=[
        html.H3("Model details"),
        html.H4("Coefficient explorer"),
        html.Div(style={"maxWidth": "420px", "marginBottom": "8px"},
                 children=[
                     dcc.Dropdown(id="dd-coef-spec", options=SPECIALTIES,
                                  value=("Primary Care"
                                         if "Primary Care" in SPECIALTIES
                                         else SPECIALTIES[0]),
                                  clearable=False)]),
        html.Div(id="lbl-coef-base",
                 style={"fontSize": "13px", "fontWeight": "600",
                        "marginBottom": "4px"}),
        dcc.Graph(id="fig-coef", config={"displayModeBar": False}),
        html.Details(open=False, children=[
            html.Summary("Full coefficient table",
                         style={"fontWeight": "600", "cursor": "pointer"}),
            dash_table.DataTable(id="tbl-coef",
                                 columns=[{"name": c, "id": c} for c in
                                          ["condition", "visit_rate",
                                           "members_with_condition"]],
                                 **TABLE_STYLE),
        ]),
        html.H4("Fit quality"),
        html.Div("High r2 = condition-driven specialty; near-zero = visits "
                 "move with headcount, not sickness.",
                 style={"fontSize": "13px", "color": "#52514e",
                        "marginBottom": "6px"}),
        dash_table.DataTable(
            columns=[{"name": c, "id": c} for c in
                     ["specialty", "r2", "base_rate_share",
                      "deflation_factor"]],
            data=FIT_ROWS, **TABLE_STYLE),
        html.H4("Evidence"),
        html.Div(style={"border": "1px solid rgba(11,11,11,0.15)",
                        "borderRadius": "10px", "padding": "12px 16px",
                        "background": "#fcfcfb", "maxWidth": "680px",
                        "fontSize": "13px"},
                 children=[
                     "People with two conditions make fewer visits than "
                     "the two solo rates added together (median 0.68x). "
                     "That is why we fit an allocation model instead of "
                     "adding rates."]),
        html.H4("Freshness"),
        html.Div(style={"border": "1px solid rgba(11,11,11,0.15)",
                        "borderRadius": "10px", "padding": "12px 16px",
                        "background": "#fcfcfb", "maxWidth": "680px",
                        "fontSize": "13px"},
                 children=[
                     html.Div(MANIFEST_LINE),
                     html.Div(f"extract row counts: " + ", ".join(
                         f"{k.replace('.parquet', '')}="
                         f"{v.get('row_count'):,}"
                         for k, v in
                         MANIFEST.get("extracts", {}).items())),
                 ]),
    ])


def simulator_tab():
    return html.Div(children=[
        html.Div(style={"display": "flex", "gap": "16px",
                        "alignItems": "center", "marginBottom": "12px"},
                 children=[
                     html.Div(style={"minWidth": "120px"}, children=[
                         dcc.Dropdown(id="dd-state", options=STATES,
                                      value=DEFAULT_STATE,
                                      clearable=False)]),
                     html.Div(style={"minWidth": "320px"}, children=[
                         dcc.Dropdown(id="dd-county", clearable=False)]),
                     html.Button("Reset", id="btn-reset", n_clicks=0,
                                 style={"padding": "6px 18px",
                                        "fontSize": "13px",
                                        "cursor": "pointer"}),
                 ]),
        html.Details(open=True, style={"marginBottom": "14px"}, children=[
            html.Summary("Scope", style={"fontWeight": "600",
                                         "cursor": "pointer"}),
            html.Div([html.P(t) for t in SCOPE_TEXT],
                     style={"fontSize": "13px", "color": "#52514e",
                            "maxWidth": "820px"}),
        ]),
        html.Div(style={"display": "flex", "gap": "20px",
                        "alignItems": "flex-start"},
                 children=[
                     html.Div(style={"flex": "0 0 30%",
                                     "background": "#fcfcfb",
                                     "border": "1px solid "
                                               "rgba(11,11,11,0.10)",
                                     "borderRadius": "10px",
                                     "padding": "14px"},
                              children=[
                                  slider_block(
                                      "s-master", "r-master", "i-master",
                                      "Master: total enrollment (%)",
                                      -30, 50,
                                      {-30: "-30", 0: "0", 25: "+25",
                                       50: "+50"}),
                                  slider_block(
                                      "s-b0", "r-b0", "i-b0",
                                      "Band 60-64 (%)", -30, 100,
                                      {-30: "-30", 0: "0", 50: "+50",
                                       100: "+100"}),
                                  slider_block(
                                      "s-b1", "r-b1", "i-b1",
                                      "Band 65-74 (%)", -30, 100,
                                      {-30: "-30", 0: "0", 50: "+50",
                                       100: "+100"}),
                                  slider_block(
                                      "s-b2", "r-b2", "i-b2",
                                      "Band 75-84 (%)", -30, 100,
                                      {-30: "-30", 0: "0", 50: "+50",
                                       100: "+100"}),
                                  slider_block(
                                      "s-b3", "r-b3", "i-b3",
                                      "Band 85+ (%)", -30, 100,
                                      {-30: "-30", 0: "0", 50: "+50",
                                       100: "+100"}),
                                  html.Div("Moving the master sets every "
                                           "band to its value; band sliders "
                                           "then adjust one band at a time.",
                                           style={"fontSize": "12px",
                                                  "color": "#898781"}),
                                  html.Div("Defaults are 0 (D11): last "
                                           "year's change is context, "
                                           "never a starting position.",
                                           style={"fontSize": "12px",
                                                  "color": "#898781"}),
                              ]),
                     html.Div(style={"flex": "1"}, children=[
                         html.Div(style={"display": "flex", "gap": "12px",
                                         "flexWrap": "wrap",
                                         "marginBottom": "14px"},
                                  children=[
                                      kpi_tile("k-enroll",
                                               "Scenario total enrollment"),
                                      kpi_tile("k-visits",
                                               "Scenario total annual "
                                               "visits"),
                                      kpi_tile("k-at",
                                               "Providers at capacity",
                                               term="ceiling"),
                                      kpi_tile("k-over",
                                               "Providers over capacity",
                                               term="ceiling"),
                                  ]),
                         html.H4("Enrollment by band"),
                         dash_table.DataTable(
                             id="tbl-enroll",
                             columns=[{"name": c, "id": c} for c in
                                      ["band", "baseline", "scenario",
                                       "delta", "pct_change"]],
                             **TABLE_STYLE),
                         dcc.RadioItems(id="rad-topn",
                                        options=[{"label": "Top 10",
                                                  "value": 10},
                                                 {"label": "Top 20",
                                                  "value": 20}],
                                        value=10, inline=True,
                                        style={"fontSize": "13px",
                                               "margin": "14px 0 6px"},
                                        inputStyle={"marginRight": "4px"},
                                        labelStyle={"marginRight": "16px"}),
                         html.Div(style={"display": "flex", "gap": "16px",
                                         "alignItems": "flex-start"},
                                  children=[
                                      html.Div(style={"flex": "1",
                                                      "minWidth": "0"},
                                               children=[
                                                   dcc.Graph(
                                                       id="fig-specialty",
                                                       config={
                                                           "displayModeBar":
                                                           False})]),
                                      html.Div(style={"flex": "1",
                                                      "minWidth": "0"},
                                               children=[
                                                   dcc.Graph(
                                                       id="fig-condition",
                                                       config={
                                                           "displayModeBar":
                                                           False})]),
                                  ]),
                         html.H4(gloss("Condition mix", "prevalence")),
                         html.Div([
                             "Members can have multiple conditions; column "
                             "does not sum to enrollment. ",
                             gloss("Movement arrows", "movement arrows"),
                             " show rank changes vs baseline."],
                             style={"fontSize": "12px", "color": "#898781",
                                    "marginBottom": "6px"}),
                         html.Details(open=False, children=[
                             html.Summary("Show numbers",
                                          style={"fontWeight": "600",
                                                 "cursor": "pointer"}),
                             dash_table.DataTable(
                                 id="tbl-condition",
                                 columns=[{"name": c, "id": c} for c in
                                          ["rank", "movement", "condition",
                                           "baseline_members",
                                           "scenario_members",
                                           "delta", "pct_change"]],
                                 **TABLE_STYLE),
                         ]),
                         html.H4([
                             gloss("Demand by specialty", "visit rate"),
                             html.Span(f" ({len(SPECIALTIES)} fitted)",
                                       style={"fontWeight": "400",
                                              "fontSize": "13px"})]),
                         html.Div(style={"maxWidth": "520px",
                                         "marginBottom": "8px"},
                                  children=[
                                      dcc.Dropdown(id="dd-specialty",
                                                   options=SPECIALTIES,
                                                   value=SPECIALTIES,
                                                   multi=True)]),
                         html.Details(open=False, children=[
                             html.Summary("Show numbers",
                                          style={"fontWeight": "600",
                                                 "cursor": "pointer"}),
                             dash_table.DataTable(
                                 id="tbl-demand",
                                 columns=[{"name": c, "id": c} for c in
                                          ["specialty", "baseline_visits",
                                           "scenario_visits", "delta",
                                           "pct_change"]],
                                 **TABLE_STYLE),
                         ]),
                         html.H4([gloss("Provider load vs capacity",
                                        "ceiling"),
                                  html.Span(" (v0 placeholder ceilings)",
                                            style={"fontWeight": "400",
                                                   "fontSize": "13px"})]),
                         html.Div(id="lbl-provider-note",
                                  style={"fontSize": "12px",
                                         "color": "#898781",
                                         "marginBottom": "6px"}),
                         dash_table.DataTable(
                             id="tbl-provider",
                             columns=[{"name": c, "id": c} for c in
                                      ["provider", "specialty",
                                       "current_visits", "estimated_max",
                                       "new_demand_coming", "room_left",
                                       "status"]],
                             tooltip_header={
                                 "estimated_max": GLOSSARY["ceiling"],
                                 "new_demand_coming": GLOSSARY["new demand"],
                                 "room_left": GLOSSARY["headroom"],
                                 "status": "HEADROOM under 90%, AT "
                                           "CAPACITY 90-100%, OVER "
                                           "CAPACITY above 100% of the "
                                           "v0 ceiling.",
                             },
                             style_data_conditional=[
                                 {"if": {"filter_query":
                                         '{status} = "HEADROOM"',
                                         "column_id": "status"},
                                  "color": "#006300",
                                  "backgroundColor":
                                      "rgba(12,163,12,0.12)",
                                  "fontWeight": "600"},
                                 {"if": {"filter_query":
                                         '{status} = "AT CAPACITY"',
                                         "column_id": "status"},
                                  "color": "#8a5a00",
                                  "backgroundColor":
                                      "rgba(250,178,25,0.18)",
                                  "fontWeight": "600"},
                                 {"if": {"filter_query":
                                         '{status} = "OVER CAPACITY"',
                                         "column_id": "status"},
                                  "color": "#d03b3b",
                                  "backgroundColor":
                                      "rgba(208,59,59,0.14)",
                                  "fontWeight": "600"},
                             ],
                             **TABLE_STYLE),
                     ]),
                 ]),
    ])


app.layout = html.Div(
    style={"maxWidth": "1200px", "margin": "0 auto", "padding": "16px",
           "fontFamily": "system-ui, sans-serif"},
    children=[
        dcc.Store(id="store-sync", data=None),
        dcc.Store(id="store-county", data=None),
        html.Div("MVP - baseline anchored to 2025 actual visits; capacity "
                 "is a v0 placeholder (observed peak). Directional tool.",
                 style={"background": "#fab219", "color": "#0b0b0b",
                        "fontWeight": "700", "textAlign": "center",
                        "padding": "8px", "borderRadius": "8px",
                        "marginBottom": "4px", "letterSpacing": "0.02em"}),
        html.Div(MANIFEST_LINE,
                 style={"fontSize": "11px", "color": "#52514e",
                        "textAlign": "center", "marginBottom": "12px"}),
        dcc.Tabs(value="tab-sim", children=[
            dcc.Tab(label="Simulator", value="tab-sim",
                    children=[simulator_tab()]),
            dcc.Tab(label="How the numbers flow", value="tab-flow",
                    children=[flow_tab()]),
            dcc.Tab(label="How it works", value="tab-method",
                    children=[methodology_tab()]),
            dcc.Tab(label="Model details", value="tab-model",
                    children=[model_tab()]),
        ]),
    ])


def build_hbar_figure(title, items):
    fig = go.Figure()
    n = len(items)
    y = list(range(n))
    names, base_seg, grow_seg, labels, dash_x, dash_y = [], [], [], [], [], []
    max_x = 1.0
    for i, (name, base, scen) in enumerate(items):
        delta = scen - base
        names.append(name)
        if scen >= base:
            base_seg.append(base)
            grow_seg.append(delta)
        else:
            base_seg.append(scen)
            grow_seg.append(0)
            dash_x.extend([base, base, None])
            dash_y.extend([i - 0.35, i + 0.35, None])
        labels.append(f"{fmt(scen)} ({delta:+,.0f})")
        max_x = max(max_x, base, scen)
    fig.add_trace(go.Bar(y=y, x=base_seg, orientation="h",
                         marker_color=GRAY, name="Baseline"))
    fig.add_trace(go.Bar(y=y, x=grow_seg, orientation="h",
                         marker_color=GREEN, name="Growth"))
    if dash_x:
        fig.add_trace(go.Scatter(x=dash_x, y=dash_y, mode="lines",
                                 line={"color": "#52514e", "dash": "dash",
                                       "width": 2},
                                 name="Baseline level"))
    for i, (name, base, scen) in enumerate(items):
        fig.add_annotation(x=max(base, scen), y=i, text=labels[i],
                           showarrow=False, xanchor="left", xshift=6,
                           font={"size": 11})
    fig.update_layout(barmode="stack",
                      height=90 + 34 * max(n, 1),
                      margin={"l": 10, "r": 10, "t": 40, "b": 30},
                      title={"text": title, "font": {"size": 14}},
                      yaxis={"tickvals": y, "ticktext": names,
                             "autorange": "reversed"},
                      xaxis={"range": [0, max_x * 1.28]},
                      legend={"orientation": "h", "y": -0.18},
                      plot_bgcolor="#fcfcfb", paper_bgcolor="#fcfcfb")
    return fig


@app.callback(
    Output("dd-county", "options"),
    Output("dd-county", "value"),
    Input("dd-state", "value"),
)
def select_state(state):
    counties = state_counties(state or DEFAULT_STATE)
    options = [{"label": county_label(c), "value": c} for c in counties]
    return options, (counties[0] if counties else None)


@app.callback(
    Output("store-county", "data"),
    Output("i-master", "children"),
    Output("i-b0", "children"),
    Output("i-b1", "children"),
    Output("i-b2", "children"),
    Output("i-b3", "children"),
    Input("dd-county", "value"),
)
def select_county(county):
    if not county:
        raise PreventUpdate
    payload = county_payload(county)
    return (payload, payload["master_label"], payload["labels"][0],
            payload["labels"][1], payload["labels"][2], payload["labels"][3])


@app.callback(
    Output("lbl-coef-base", "children"),
    Output("fig-coef", "figure"),
    Output("tbl-coef", "data"),
    Input("dd-coef-spec", "value"),
)
def coef_explorer(spec):
    spec = spec or SPECIALTIES[0]
    base = BASE_RATE.get(spec, 0.0)
    base_line = (f"Base visits per member (everyone, before conditions): "
                 f"{base:.2f}")
    rows = RATES[(RATES["cms_specialty"] == spec)
                 & (~RATES["condition"].isin(["BASE_RATE"]))]
    rows = rows.sort_values("visit_rate", ascending=False)
    top = rows.head(15)
    names = [cond_label(str(c)) if c != "OTHER_CONDITION"
             else "Other conditions (pooled)" for c in top["condition"]]
    fig = go.Figure(go.Bar(
        y=list(range(len(top))), x=list(top["visit_rate"]),
        orientation="h", marker_color=GREEN))
    fig.update_layout(
        height=90 + 30 * max(len(top), 1),
        margin={"l": 10, "r": 10, "t": 40, "b": 30},
        title={"text": f"{spec}: top condition visit rates",
               "font": {"size": 14}},
        yaxis={"tickvals": list(range(len(top))), "ticktext": names,
               "autorange": "reversed"},
        plot_bgcolor="#fcfcfb", paper_bgcolor="#fcfcfb")
    table = [{"condition": ("Other conditions (pooled)"
                            if str(r.condition) == "OTHER_CONDITION"
                            else cond_label(str(r.condition))),
              "visit_rate": f"{float(r.visit_rate):.3f}",
              "members_with_condition": fmt(r.members_with_condition)}
             for r in rows.itertuples()]
    return base_line, fig, table


@app.callback(
    Output("s-master", "value"),
    Output("s-b0", "value"),
    Output("s-b1", "value"),
    Output("s-b2", "value"),
    Output("s-b3", "value"),
    Output("store-sync", "data"),
    Output("r-master", "children"),
    Output("r-b0", "children"),
    Output("r-b1", "children"),
    Output("r-b2", "children"),
    Output("r-b3", "children"),
    Output("k-enroll", "children"),
    Output("k-visits", "children"),
    Output("k-at", "children"),
    Output("k-over", "children"),
    Output("tbl-enroll", "data"),
    Output("tbl-condition", "data"),
    Output("fig-specialty", "figure"),
    Output("fig-condition", "figure"),
    Output("tbl-demand", "data"),
    Output("tbl-provider", "data"),
    Output("lbl-provider-note", "children"),
    Input("s-master", "value"),
    Input("s-b0", "value"),
    Input("s-b1", "value"),
    Input("s-b2", "value"),
    Input("s-b3", "value"),
    Input("btn-reset", "n_clicks"),
    Input("dd-specialty", "value"),
    Input("rad-topn", "value"),
    Input("store-county", "data"),
    State("store-sync", "data"),
)
def update(master, b0, b1, b2, b3, _reset_clicks, selected_specialties,
           top_n, payload, sync_token):
    if not payload:
        raise PreventUpdate
    trigger = ctx.triggered_id
    master = master if master is not None else MASTER_DEFAULT
    bands = [v if v is not None else BAND_DEFAULTS[i]
             for i, v in enumerate([b0, b1, b2, b3])]

    slider_out = [no_update] * 5
    store_out = no_update
    if trigger == "btn-reset":
        bands = list(BAND_DEFAULTS)
        slider_out = [MASTER_DEFAULT] + list(BAND_DEFAULTS)
        store_out = MASTER_DEFAULT if master != MASTER_DEFAULT else None
    elif trigger == "s-master":
        if sync_token is not None and master == sync_token:
            store_out = None
        else:
            bands = [master] * len(BANDS)
            slider_out = [no_update] + [master] * len(BANDS)
            store_out = None

    base_members = payload["members"]
    prev = payload["prev"]
    other_prev = payload["other_prev"]
    cal = payload["cal"]
    base_demand = payload["base_demand"]
    base_conditions = payload["base_conditions"]
    base_other = payload["base_other"]
    base_ranks = payload["base_ranks"]

    members = [max(0.0, base_members[i] * (1 + bands[i] / 100.0))
               for i in range(len(BANDS))]
    demand, cond_now, other_now = compute_demand(members, prev, other_prev,
                                                 cal)
    deltas = {s: demand[s] - base_demand.get(s, 0.0) for s in SPECIALTIES}

    total_enroll = sum(members)
    total_base = sum(base_members)
    readout_master = (
        f"Total: {fmt(total_enroll)} members "
        f"({pct((total_enroll - total_base) / total_base) if total_base else 'n/a'} vs baseline)")
    readouts = [f"{BAND_NAMES[i]}: {bands[i]:+d}% -> {fmt(members[i])} "
                f"members" for i in range(len(BANDS))]

    enroll_rows = []
    for i, band in enumerate(BAND_NAMES):
        base = base_members[i]
        d = members[i] - base
        enroll_rows.append({
            "band": band, "baseline": fmt(base), "scenario": fmt(members[i]),
            "delta": f"{d:+,.0f}",
            "pct_change": pct(d / base) if base else "n/a"})

    n_show = top_n if top_n is not None else 10
    order, cur_ranks = ranks_desc(cond_now)
    condition_rows = []
    for pos, c in enumerate(order[:n_show]):
        base_c = base_conditions.get(c, 0.0)
        d = cond_now[c] - base_c
        moved = base_ranks.get(c, cur_ranks[c]) - cur_ranks[c]
        if moved > 0:
            movement = f"^{moved}"
        elif moved < 0:
            movement = f"v{-moved}"
        else:
            movement = "-"
        condition_rows.append({
            "rank": pos + 1,
            "movement": movement,
            "condition": cond_label(c),
            "baseline_members": fmt(base_c),
            "scenario_members": fmt(cond_now[c]),
            "delta": f"{d:+,.0f}",
            "pct_change": pct(d / base_c) if base_c else "n/a"})
    rest = order[n_show:]
    if rest:
        rest_base = sum(base_conditions.get(c, 0.0) for c in rest)
        rest_now = sum(cond_now[c] for c in rest)
        condition_rows.append({
            "rank": "", "movement": "",
            "condition": f"Other listed ({len(rest)} conditions)",
            "baseline_members": fmt(rest_base),
            "scenario_members": fmt(rest_now),
            "delta": f"{rest_now - rest_base:+,.0f}",
            "pct_change": ""})
    condition_rows.append({
        "rank": "", "movement": "",
        "condition": "Other conditions (pooled)",
        "baseline_members": fmt(base_other),
        "scenario_members": fmt(other_now),
        "delta": f"{other_now - base_other:+,.0f}",
        "pct_change": (pct((other_now - base_other) / base_other)
                       if base_other else "")})

    selected = set(selected_specialties or [])
    demand_rows = []
    for s in SPECIALTIES:
        if s not in selected:
            continue
        base_s = base_demand.get(s, 0.0)
        demand_rows.append({
            "specialty": s, "baseline_visits": fmt(base_s),
            "scenario_visits": fmt(demand[s]),
            "delta": f"{deltas[s]:+,.0f}",
            "pct_change": pct(deltas[s] / base_s) if base_s else "n/a"})

    n_at = 0
    n_over = 0
    no_weight = 0
    provider_rows = []
    for p in payload["providers"]:
        w = p["weight"]
        if w is None:
            no_weight += 1
            new_demand = None
        else:
            new_demand = deltas.get(p["spec"], 0.0) * w
        load = p["visits"] + (new_demand or 0.0)
        utilization = load / p["ceiling"] if p["ceiling"] else 0.0
        status = status_of(utilization)
        if status == "AT CAPACITY":
            n_at += 1
        if status == "OVER CAPACITY":
            n_over += 1
        if p["spec"] in selected:
            room = p["ceiling"] - load
            provider_rows.append({
                "_visits": p["visits"],
                "provider": p["id"], "specialty": p["spec"],
                "current_visits": fmt(p["visits"]),
                "estimated_max": f"~{fmt(p['ceiling'])}",
                "new_demand_coming": (f"{new_demand:+,.0f}"
                                      if new_demand is not None else "-"),
                "room_left": (fmt(room) if room >= 0
                              else f"short by {fmt(-room)}"),
                "status": status})
    total_in_selection = len(provider_rows)
    provider_rows = sorted(provider_rows,
                           key=lambda r: -r["_visits"])[:TOP_PROVIDERS_SHOWN]
    for r in provider_rows:
        r.pop("_visits", None)
    note = (f"{payload['prov_mode']}; showing top {len(provider_rows)} of "
            f"{total_in_selection} in selection by 2025 visits; "
            f"{no_weight} carry no intake weight (zero 2025 new-patient "
            f"visits in their cell - excluded from routing)")

    spec_items = sorted(
        ((s, base_demand.get(s, 0.0), demand[s])
         for s in SPECIALTIES if s in selected),
        key=lambda t: -t[2])[:n_show]
    cond_items = [(cond_label(c), base_conditions.get(c, 0.0), cond_now[c])
                  for c in order[:n_show]]
    fig_specialty = build_hbar_figure(
        f"Specialty demand - top {n_show}", spec_items)
    fig_condition = build_hbar_figure(
        f"Condition members - top {n_show}", cond_items)

    return (slider_out[0], slider_out[1], slider_out[2], slider_out[3],
            slider_out[4], store_out,
            readout_master, readouts[0], readouts[1], readouts[2],
            readouts[3],
            fmt(total_enroll), fmt(sum(demand.values())), str(n_at),
            str(n_over),
            enroll_rows, condition_rows, fig_specialty, fig_condition,
            demand_rows, provider_rows, note)


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8051, debug=False)
