-- ============================================================
-- 04 - ms_ref_county_classification                          [SQL / BigQuery]
-- WHAT   : Classify every scope-state county into CMS county_type
--          (Large Metro / Metro / Micro / Rural / CEAC) + compliance_threshold
--          + county_radius_miles.
-- WHY    : county_type drives distance thresholds and the 90% / 85% access bar.
-- SOURCE : bigquery-public-data.geo_us_boundaries.counties
--          bigquery-public-data.census_bureau_acs.county_2020_5yr
--          ms_ref_hsd_required_counts   (HSD county_type is authoritative)
-- OUTPUT : ms_ref_county_classification   grain: county_fips
-- NOTE   : Filter state_fips_code IN scope FIPS. Prefer county_type from the HSD
--          load (01); Census is fallback only. Carries state_cd.
-- ============================================================
-- TODO: implement
