-- ============================================================
-- 05 - ms_ref_zip_reference                                  [SQL / BigQuery]
-- WHAT   : Master zip lookup -- centroid lat/long, area, radius, and zip -> county
--          via spatial intersection (largest area overlap wins).
-- WHY    : Single geo source; both stg_beneficiaries and stg_providers join here
--          for lat/long and county. The distance test uses zip centroids.
-- SOURCE : bigquery-public-data.geo_us_boundaries.zip_codes
--          bigquery-public-data.census_bureau_acs.zip_codes_2018_5yr
--          bigquery-public-data.geo_us_boundaries.counties
--          ms_ref_county_classification
-- OUTPUT : ms_ref_zip_reference   grain: zip_code   (carries state_cd, county_fips)
-- NOTE   : counties filtered to scope FIPS; ST_INTERSECTS intentionally pulls in
--          border zips of neighboring states (as GA/AL did for FL).
-- ============================================================
-- TODO: implement
