-- ============================================================
-- 06 - ms_ref_county_name_crosswalk                          [SQL / BigQuery]
-- WHAT   : Reconcile Aetna county names to canonical county_fips for all scope
--          states (handles name mismatches + no-coverage flags).
-- WHY    : stg_providers derives county_fips from Aetna county_nm via this table.
-- SOURCE : bigquery-public-data.geo_us_boundaries.counties  (canonical name + fips)
--          + distinct Aetna county names from the mbr source
-- OUTPUT : ms_ref_county_name_crosswalk   grain: state_cd x aetna_county_nm
-- NOTE   : MUST key on state_cd + name -- county names collide across states
--          (Lake, Madison, Union, Monroe, Marion). May need a small mismatch CSV.
-- ============================================================
-- TODO: implement
