-- ============================================================
-- 07 - ms_mbr_with_all_zips                                  [SQL / BigQuery]
-- WHAT   : Supply source. Enrich mbr_with_zip with every provider practice zip
--          from mdcr_base_provider_mdcr_ntwk.
-- WHY    : Providers with multiple locations contribute distance from each zip,
--          not just their primary.
-- SOURCE : A870800_medicare_supply_demand_mbr_with_zip   (ours; holds all states)
--          mdcr_base_provider_mdcr_ntwk
-- OUTPUT : ms_mbr_with_all_zips   grain: provider x zip x network match
-- NOTE   : Same recipe as FL Step5, but WHERE state IN scope states (not just FL).
-- ============================================================
-- TODO: implement
