-- ============================================================
-- 09 - ms_stg_providers_multi_specialty                      [SQL / BigQuery]
-- WHAT   : Supply side. One row per provider x cms_specialty x plan_type, with
--          zip lat/long, county_fips, county_type, state_cd.
-- WHY    : Multi-specialty explosion so a provider counts toward every specialty
--          it serves, not just its primary.
-- SOURCE : ms_mbr_with_all_zips + edp-prod-hcbstorage.* (RPDB_RPNPRAC, EPDB_PRVDR,
--          RPDB_RINPR, PRVDR_TY_X_SPCLTY, GLOBAL_LOOKUP)
--          + ms_ref_specialty_crosswalk_expanded + ms_ref_county_name_crosswalk
--          + ms_ref_zip_reference
-- OUTPUT : ms_stg_providers_multi_specialty   grain: provider x cms_specialty x plan_type
-- NOTE   : county_fips join via the county-name crosswalk MUST include state_cd.
-- ============================================================
-- TODO: implement
